// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package goapb

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ErrorResponse message defines the error encoded in the gRPC response that
// correspond to the errors created by the generated code. This is mainly
// intended for the clients to decode error responses.
type ErrorResponse struct {
	// name is the name for that class of errors.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// id is the unique error instance identifier.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// msg describes the specific error occurrence.
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// temporary indicates whether the error is temporary.
	Temporary bool `protobuf:"varint,4,opt,name=temporary,proto3" json:"temporary,omitempty"`
	// timeout indicates whether the error is a timeout.
	Timeout bool `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// fault indicates whether the error is a server-side fault.
	Fault                bool     `protobuf:"varint,6,opt,name=fault,proto3" json:"fault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_error_a11b9d65941b6837, []int{0}
}
func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (dst *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(dst, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ErrorResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ErrorResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ErrorResponse) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

func (m *ErrorResponse) GetTimeout() bool {
	if m != nil {
		return m.Timeout
	}
	return false
}

func (m *ErrorResponse) GetFault() bool {
	if m != nil {
		return m.Fault
	}
	return false
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "goapb.ErrorResponse")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_error_a11b9d65941b6837) }

var fileDescriptor_error_a11b9d65941b6837 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0x3d, 0x0e, 0xc2, 0x30,
	0x0c, 0x86, 0x61, 0xa5, 0x7f, 0x50, 0x23, 0x10, 0xb2, 0x18, 0x3c, 0x30, 0x54, 0x4c, 0x9d, 0x58,
	0x38, 0x03, 0x17, 0xe8, 0x0d, 0x52, 0x35, 0x54, 0x95, 0x48, 0x1d, 0x39, 0xe9, 0xc0, 0x39, 0xb8,
	0x30, 0xaa, 0x11, 0x62, 0xfb, 0xde, 0xc7, 0x8b, 0x61, 0xe7, 0x44, 0x58, 0xae, 0x41, 0x38, 0x31,
	0x96, 0x23, 0xdb, 0xd0, 0x5f, 0xde, 0x06, 0xf6, 0xf7, 0x95, 0x3b, 0x17, 0x03, 0xcf, 0xd1, 0x21,
	0x42, 0x31, 0x5b, 0xef, 0xc8, 0x34, 0xa6, 0xad, 0x3b, 0xdd, 0x78, 0x80, 0x6c, 0x1a, 0x28, 0x53,
	0xc9, 0xa6, 0x01, 0x8f, 0x90, 0xfb, 0x38, 0x52, 0xae, 0xb0, 0x4e, 0x3c, 0x43, 0x9d, 0x9c, 0x0f,
	0x2c, 0x56, 0x5e, 0x54, 0x34, 0xa6, 0xdd, 0x76, 0x7f, 0x40, 0x82, 0x4d, 0x9a, 0xbc, 0xe3, 0x25,
	0x51, 0xa9, 0xb7, 0x5f, 0xe2, 0x09, 0xca, 0x87, 0x5d, 0x9e, 0x89, 0x2a, 0xf5, 0x6f, 0xf4, 0x95,
	0xfe, 0x78, 0xfb, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x9b, 0xa7, 0xd8, 0xb2, 0x00, 0x00, 0x00,
}
