// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: goadesign_goa_error.proto

// NOTE: If there are any changes to this file, run the protoc command as
// below from the pb directory to generate the error.pb.go file.
//
// $  protoc --proto_path=. --go_out=. --go_opt=paths=source_relative  error.proto

package goapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponse message defines the error encoded in the gRPC response that
// correspond to the errors created by the generated code. This is mainly
// intended for the clients to decode error responses.
type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name for that class of errors.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// id is the unique error instance identifier.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// msg describes the specific error occurrence.
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// temporary indicates whether the error is temporary.
	Temporary bool `protobuf:"varint,4,opt,name=temporary,proto3" json:"temporary,omitempty"`
	// timeout indicates whether the error is a timeout.
	Timeout bool `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// fault indicates whether the error is a server-side fault.
	Fault bool `protobuf:"varint,6,opt,name=fault,proto3" json:"fault,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goadesign_goa_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goadesign_goa_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_goadesign_goa_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ErrorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ErrorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ErrorResponse) GetTemporary() bool {
	if x != nil {
		return x.Temporary
	}
	return false
}

func (x *ErrorResponse) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

func (x *ErrorResponse) GetFault() bool {
	if x != nil {
		return x.Fault
	}
	return false
}

var File_goadesign_goa_error_proto protoreflect.FileDescriptor

var file_goadesign_goa_error_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x6f, 0x61, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x67, 0x6f, 0x61, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f, 0x61,
	0x70, 0x62, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74,
	0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x67, 0x6f, 0x61,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goadesign_goa_error_proto_rawDescOnce sync.Once
	file_goadesign_goa_error_proto_rawDescData = file_goadesign_goa_error_proto_rawDesc
)

func file_goadesign_goa_error_proto_rawDescGZIP() []byte {
	file_goadesign_goa_error_proto_rawDescOnce.Do(func() {
		file_goadesign_goa_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_goadesign_goa_error_proto_rawDescData)
	})
	return file_goadesign_goa_error_proto_rawDescData
}

var file_goadesign_goa_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_goadesign_goa_error_proto_goTypes = []interface{}{
	(*ErrorResponse)(nil), // 0: goapb.ErrorResponse
}
var file_goadesign_goa_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goadesign_goa_error_proto_init() }
func file_goadesign_goa_error_proto_init() {
	if File_goadesign_goa_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goadesign_goa_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goadesign_goa_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goadesign_goa_error_proto_goTypes,
		DependencyIndexes: file_goadesign_goa_error_proto_depIdxs,
		MessageInfos:      file_goadesign_goa_error_proto_msgTypes,
	}.Build()
	File_goadesign_goa_error_proto = out.File
	file_goadesign_goa_error_proto_rawDesc = nil
	file_goadesign_goa_error_proto_goTypes = nil
	file_goadesign_goa_error_proto_depIdxs = nil
}
