version: "2"
linters:
  enable:
    - errorlint
    - errcheck
    - staticcheck
    - unparam      # Detects unused parameters
    - unused       # Detects unused constants, variables, functions and types
    - ineffassign  # Detects ineffectual assignments
  settings:
    staticcheck:
      checks:
        - "-ST1001"

