package codegen

import (
	"bytes"
	"strings"
	"testing"
)

// normalizeLineEndings converts Windows line endings to Unix line endings
func normalizeLineEndings(s string) string {
	return strings.ReplaceAll(s, "\r\n", "\n")
}

func TestHeader(t *testing.T) {
	const (
		title         = "test title"
		noTitleHeader = `package testpackage

`
		singleImportHeader = `package testpackage

import 	"test"

`
		manyImportsHeader = `package testpackage

import (
	"test"
	"other"
)

`

		pathImportHeader = `package testpackage

import 	"import/with/slashes"

`

		pathImportsHeader = `package testpackage

import (
	"import/with/slashes"
	"other/import/with/slashes"
)

`

		pathNamedImportHeader = `package testpackage

import 	myname "import/with/slashes"

`
		pathNamedImportsHeader = `package testpackage

import (
	myname "import/with/slashes"
	myothername "other/import/with/slashes"
)

`
	)
	var (
		titleHeader = `// Code generated by goa, DO NOT EDIT.
//
// test title
//
// Command:
// goa

package testpackage

`
		imprt = []*ImportSpec{
			{Path: "test"},
		}
		imports = []*ImportSpec{
			{Path: "test"},
			{Path: "other"},
		}
		pathImport = []*ImportSpec{
			{Path: "import/with/slashes"},
		}
		pathImports = []*ImportSpec{
			{Path: "import/with/slashes"},
			{Path: "other/import/with/slashes"},
		}
		pathNamedImport = []*ImportSpec{
			{Name: "myname", Path: "import/with/slashes"},
		}
		pathNamedImports = []*ImportSpec{
			{Name: "myname", Path: "import/with/slashes"},
			{Name: "myothername", Path: "other/import/with/slashes"},
		}
	)
	cases := map[string]struct {
		Title    string
		Imports  []*ImportSpec
		Expected string
	}{
		"no-title":           {Expected: noTitleHeader},
		"title":              {Title: title, Expected: titleHeader},
		"single-import":      {Imports: imprt, Expected: singleImportHeader},
		"many-imports":       {Imports: imports, Expected: manyImportsHeader},
		"path-import":        {Imports: pathImport, Expected: pathImportHeader},
		"path-imports":       {Imports: pathImports, Expected: pathImportsHeader},
		"path-named-import":  {Imports: pathNamedImport, Expected: pathNamedImportHeader},
		"path-named-imports": {Imports: pathNamedImports, Expected: pathNamedImportsHeader},
	}
	for k, tc := range cases {
		t.Run(k, func(t *testing.T) {
			buf := new(bytes.Buffer)
			s := Header(tc.Title, "testpackage", tc.Imports)
			s.Write(buf) // nolint: errcheck
			actual := buf.String()
			// Normalize line endings for cross-platform compatibility
			actual = normalizeLineEndings(actual)
			expected := normalizeLineEndings(tc.Expected)
			if actual != expected {
				t.Errorf("%s: got %#v, expected %#v", k, actual, expected)
			}
		})
	}
}

func TestHeaderKeepsOneImportPerPath(t *testing.T) {
	section := Header("", "testpackage", []*ImportSpec{
		{Path: "encoding/json"},
		{Name: "json", Path: "encoding/json"},
	})
	var source bytes.Buffer
	if err := section.Write(&source); err != nil {
		t.Fatal(err)
	}
	if count := strings.Count(source.String(), `"encoding/json"`); count != 1 {
		t.Fatalf("encoding/json import count = %d, want 1\n%s", count, source.String())
	}
	if !strings.Contains(source.String(), `json "encoding/json"`) {
		t.Fatalf("encoding/json import did not keep its explicit name\n%s", source.String())
	}
}

func TestAddImportKeepsOneImportPerPath(t *testing.T) {
	section := Header("", "testpackage", []*ImportSpec{{Path: "encoding/json"}})
	AddImport(section, &ImportSpec{Name: "json", Path: "encoding/json"})
	var source bytes.Buffer
	if err := section.Write(&source); err != nil {
		t.Fatal(err)
	}
	if count := strings.Count(source.String(), `"encoding/json"`); count != 1 {
		t.Fatalf("encoding/json import count = %d, want 1\n%s", count, source.String())
	}
	if !strings.Contains(source.String(), `json "encoding/json"`) {
		t.Fatalf("encoding/json import did not keep its explicit name\n%s", source.String())
	}

	t.Run("different explicit names", func(t *testing.T) {
		section := Header("", "testpackage", []*ImportSpec{{Name: "first", Path: "example.com/log"}})
		defer func() {
			if recovered := recover(); recovered == nil {
				t.Fatal("AddImport did not reject different explicit names for one package")
			}
		}()
		AddImport(section, &ImportSpec{Name: "second", Path: "example.com/log"})
	})
}
