// This file verifies one complete service planning run assigns generated
// package paths before any service declarations are collected.
package service

import (
	"path"
	"testing"

	"github.com/stretchr/testify/require"

	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/dsl"
	"goa.design/goa/v3/eval"
	"goa.design/goa/v3/expr"
)

type (
	// servicePathTestInput names one API and service included in a complete
	// planning run.
	servicePathTestInput struct {
		api     string
		service string
	}
)

// TestNewPlansAssignsStableServicePackagePaths verifies distinct service names
// that have the same normal path receive stable unique paths. A service whose
// name naturally contains a numeric suffix keeps that path.
func TestNewPlansAssignsStableServicePackagePaths(t *testing.T) {
	forward := plannedServicePackagePaths(t, []servicePathTestInput{
		{api: "dash api", service: "read-value"},
		{api: "underscore api", service: "read_value"},
		{api: "numbered api", service: "read_value2"},
	})
	reverse := plannedServicePackagePaths(t, []servicePathTestInput{
		{api: "numbered api", service: "read_value2"},
		{api: "underscore api", service: "read_value"},
		{api: "dash api", service: "read-value"},
	})

	require.Equal(t, forward, reverse)
	require.Equal(t, map[string]string{
		"read-value":  "generated.local/gen/read_value",
		"read_value":  "generated.local/gen/read_value3",
		"read_value2": "generated.local/gen/read_value2",
	}, forward)
}

// TestNewPlansSharesServicePackagePathAcrossRoots verifies the same exact
// service name uses one generated package when two APIs contribute to it.
func TestNewPlansSharesServicePackagePathAcrossRoots(t *testing.T) {
	forward := plannedServicePackagePaths(t, []servicePathTestInput{
		{api: "first api", service: "Shared"},
		{api: "second api", service: "Shared"},
	})
	reverse := plannedServicePackagePaths(t, []servicePathTestInput{
		{api: "second api", service: "Shared"},
		{api: "first api", service: "Shared"},
	})

	require.Equal(t, forward, reverse)
	require.Equal(t, map[string]string{
		"first api/Shared":  "generated.local/gen/shared",
		"second api/Shared": "generated.local/gen/shared",
	}, forward)
}

// TestNewPlansRejectsRepeatedAPIService verifies two roots cannot contribute
// indistinguishable declarations for the same API and service.
func TestNewPlansRejectsRepeatedAPIService(t *testing.T) {
	first := servicePathTestRoot(t, "same api", "Shared")
	second := servicePathTestRoot(t, "same api", "Shared")
	generation := mustTestGeneration(t, "generated.local/gen", []eval.Root{first, second})

	_, err := NewPlans(
		generation,
		PlanInput{Root: first, Examples: expr.NewExampleGenerator(first.API.RandomizerFactory)},
		PlanInput{Root: second, Examples: expr.NewExampleGenerator(second.API.RandomizerFactory)},
	)

	require.EqualError(t, err, `service "Shared" in API "same api" is planned by more than one root`)
}

// TestNewPlansKeepsNoncollidingServicePackagePaths verifies ordinary service
// names keep the paths generated by earlier Goa versions.
func TestNewPlansKeepsNoncollidingServicePackagePaths(t *testing.T) {
	paths := plannedServicePackagePaths(t, []servicePathTestInput{
		{api: "storage api", service: "Storage"},
		{api: "audit api", service: "AuditLog"},
	})

	require.Equal(t, map[string]string{
		"Storage":  "generated.local/gen/storage",
		"AuditLog": "generated.local/gen/audit_log",
	}, paths)
}

// plannedServicePackagePaths builds and freezes one complete planning run, then
// returns the retained package path for every input service.
func plannedServicePackagePaths(t *testing.T, inputs []servicePathTestInput) map[string]string {
	t.Helper()
	roots := make([]*expr.RootExpr, len(inputs))
	evaluated := make([]eval.Root, len(inputs))
	planInputs := make([]PlanInput, len(inputs))
	for index, input := range inputs {
		root := servicePathTestRoot(t, input.api, input.service)
		roots[index] = root
		evaluated[index] = root
		planInputs[index] = PlanInput{
			Root:     root,
			Examples: expr.NewExampleGenerator(root.API.RandomizerFactory),
		}
	}
	generation := mustTestGeneration(t, "generated.local/gen", evaluated)
	plans, err := NewPlans(generation, planInputs...)
	require.NoError(t, err)
	require.NoError(t, generation.Freeze())

	paths := make(map[string]string, len(inputs))
	sharedNames := make(map[string]int)
	for _, input := range inputs {
		sharedNames[input.service]++
	}
	for index, plan := range plans {
		service := roots[index].Service(inputs[index].service)
		serviceImport, _, err := plan.ServicePackageImports(service)
		require.NoError(t, err)
		require.NoError(t, plan.Link())
		require.Equal(t, path.Base(serviceImport.Path), plan.Services().Get(service.Name).PathName)
		key := inputs[index].service
		if sharedNames[key] > 1 {
			key = inputs[index].api + "/" + key
		}
		paths[key] = serviceImport.Path
	}
	return paths
}

// servicePathTestRoot creates one evaluated design with a single service and
// gives its API the identity used to order shared package declarations.
func servicePathTestRoot(t *testing.T, api, service string) *expr.RootExpr {
	t.Helper()
	root := codegen.RunDSL(t, func() {
		dsl.Service(service, func() {
			dsl.Method("Read", func() {
				dsl.Payload(func() {
					dsl.Attribute("value", dsl.String)
				})
			})
		})
	})
	root.API.Name = api
	return root
}
