package openapi

import (
	"fmt"
	"path"
	"strings"

	"goa.design/goa/v3/expr"
)

type (
	// Version identifies an OpenAPI specification version generated by Goa.
	Version string

	// Spec describes one OpenAPI document to generate: the specification
	// version it conforms to and its output path. The path is
	// slash-separated, relative to the gen directory and does not include
	// an extension: each document is written both as <path>.json and
	// <path>.yaml.
	Spec struct {
		// Version is the OpenAPI specification version of the document.
		Version Version
		// Path is the output path of the document relative to the gen
		// directory, without extension.
		Path string
	}
)

const (
	// Version20 identifies the Swagger (OpenAPI) 2.0 specification.
	Version20 Version = "2.0"
	// Version30 identifies the OpenAPI 3.0.3 specification.
	Version30 Version = "3.0"
	// Version32 identifies the OpenAPI 3.2.0 specification.
	Version32 Version = "3.2"
)

const (
	// DefaultPath20 is the default output path of the Swagger 2.0
	// document relative to the gen directory, without extension.
	DefaultPath20 = "http/openapi"
	// DefaultPath30 is the default output path of the OpenAPI 3.0.3
	// document relative to the gen directory, without extension.
	DefaultPath30 = "http/openapi3"
	// DefaultPath32 is the default output path of the OpenAPI 3.2.0
	// document relative to the gen directory, without extension.
	DefaultPath32 = "http/openapi3.2"
)

// versionsMetaKey is the API meta key used to select the generated OpenAPI
// specification versions.
const versionsMetaKey = "openapi:versions"

// pathMetaPrefix is the prefix of the API meta keys used to override the
// output paths of the generated OpenAPI documents.
const pathMetaPrefix = "openapi:path:"

// specDefaults lists the supported OpenAPI versions with their default output
// paths in generation order. The order matters: the example generator used to
// compute schema examples is stateful and generating the documents in a
// stable order keeps the examples of each document stable.
var specDefaults = []Spec{
	{Version20, DefaultPath20},
	{Version30, DefaultPath30},
	{Version32, DefaultPath32},
}

// Specs computes the OpenAPI documents to generate from the given API meta.
// The "openapi:versions" meta selects the generated versions and defaults to
// all supported versions. The "openapi:path:<version>" meta overrides the
// output path of the corresponding document. Specs returns the documents in
// generation order (2.0, 3.0 then 3.2) and errors on invalid version or path
// values.
func Specs(meta expr.MetaExpr) ([]Spec, error) {
	if err := validatePathKeys(meta); err != nil {
		return nil, err
	}
	selected, err := selectedVersions(meta)
	if err != nil {
		return nil, err
	}
	specs := make([]Spec, 0, len(selected))
	seen := make(map[string]Version, len(selected))
	for _, d := range specDefaults {
		if !selected[d.Version] {
			continue
		}
		p, err := specPath(meta, d)
		if err != nil {
			return nil, err
		}
		if prev, ok := seen[p]; ok {
			return nil, fmt.Errorf("OpenAPI versions %s and %s use the same output path %q: override one with meta %q", prev, d.Version, p, pathMetaPrefix+string(d.Version))
		}
		seen[p] = d.Version
		specs = append(specs, Spec{d.Version, p})
	}
	return specs, nil
}

// selectedVersions computes the set of OpenAPI versions to generate from the
// "openapi:versions" meta. It errors on unknown version values.
func selectedVersions(meta expr.MetaExpr) (map[Version]bool, error) {
	selected := make(map[Version]bool, len(specDefaults))
	vals, ok := meta[versionsMetaKey]
	if !ok {
		for _, d := range specDefaults {
			selected[d.Version] = true
		}
		return selected, nil
	}
	for _, val := range vals {
		if !knownVersion(val) {
			return nil, fmt.Errorf("invalid value %q for meta %q: valid values are %q, %q and %q", val, versionsMetaKey, Version20, Version30, Version32)
		}
		selected[Version(val)] = true
	}
	return selected, nil
}

// specPath computes the output path of the document with the given defaults,
// honoring the "openapi:path:<version>" meta. It errors when the override is
// not a clean extension-less path relative to the gen directory.
func specPath(meta expr.MetaExpr, d Spec) (string, error) {
	key := pathMetaPrefix + string(d.Version)
	val, ok := meta.Last(key)
	if !ok {
		return d.Path, nil
	}
	if val == "" {
		return "", fmt.Errorf("invalid value for meta %q: path cannot be empty", key)
	}
	if strings.HasPrefix(val, "/") {
		return "", fmt.Errorf("invalid value %q for meta %q: path must be relative to the gen directory", val, key)
	}
	if cleaned := path.Clean(val); cleaned == "." || cleaned == ".." || strings.HasPrefix(cleaned, "../") {
		return "", fmt.Errorf("invalid value %q for meta %q: path must not escape the gen directory", val, key)
	}
	switch path.Ext(val) {
	case ".json", ".yaml", ".yml":
		return "", fmt.Errorf("invalid value %q for meta %q: path must not include an extension, both %s.json and %s.yaml are generated", val, key, val, val)
	}
	return path.Clean(val), nil
}

// validatePathKeys errors when the given meta contains an
// "openapi:path:<version>" key with an unknown version suffix. This catches
// typos such as "openapi:path:3.0.3" which would otherwise be silently
// ignored.
func validatePathKeys(meta expr.MetaExpr) error {
	for key := range meta {
		if strings.HasPrefix(key, pathMetaPrefix) && !knownVersion(key[len(pathMetaPrefix):]) {
			return fmt.Errorf("invalid meta key %q: valid OpenAPI versions are %q, %q and %q", key, Version20, Version30, Version32)
		}
	}
	return nil
}

// knownVersion reports whether val names a supported OpenAPI version.
func knownVersion(val string) bool {
	for _, d := range specDefaults {
		if val == string(d.Version) {
			return true
		}
	}
	return false
}
