swagger: "2.0"
info:
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /resumes:
    get:
      tags:
      - resume
      summary: list resume
      description: List all stored resumes
      operationId: resume#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResumeStoredResumeResponseCollection'
      schemes:
      - http
    post:
      tags:
      - resume
      summary: add resume
      description: Add n number of resumes and return their IDs. This is a multipart
        request and each part has field name 'resume' and contains the encoded resume
        to be added.
      operationId: resume#add
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/ResumeRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: integer
              example: 6588713156643713584
              format: int64
      schemes:
      - http
definitions:
  EducationRequestBody:
    title: EducationRequestBody
    type: object
    properties:
      institution:
        type: string
        description: Name of the institution
        example: Et consequatur ad.
      major:
        type: string
        description: Major name
        example: Et ipsa.
    example:
      institution: Et officiis consectetur quidem quod sapiente quia.
      major: Rerum beatae.
    required:
    - institution
    - major
  EducationResponse:
    title: EducationResponse
    type: object
    properties:
      institution:
        type: string
        description: Name of the institution
        example: Reprehenderit molestiae placeat perspiciatis rerum.
      major:
        type: string
        description: Major name
        example: Aliquam ratione alias.
    example:
      institution: Doloremque est est et placeat dolorum deserunt.
      major: Consectetur quasi sed qui.
    required:
    - institution
    - major
  ExperienceRequestBody:
    title: ExperienceRequestBody
    type: object
    properties:
      company:
        type: string
        description: Name of the company
        example: Sequi nihil et doloremque quidem fugit delectus.
      duration:
        type: integer
        description: Duration (in years) in the company
        example: 7991684391525051755
        format: int64
      role:
        type: string
        description: Name of the role in the company
        example: Necessitatibus officiis similique facilis sapiente.
    example:
      company: Ut quod quaerat.
      duration: 2762064478437738550
      role: Et hic itaque quis voluptatem ducimus est.
    required:
    - company
    - role
    - duration
  ExperienceResponse:
    title: ExperienceResponse
    type: object
    properties:
      company:
        type: string
        description: Name of the company
        example: Ducimus quo hic aut cumque dicta autem.
      duration:
        type: integer
        description: Duration (in years) in the company
        example: 485875295432613167
        format: int64
      role:
        type: string
        description: Name of the role in the company
        example: Ut voluptas fuga ipsa expedita aut.
    example:
      company: Nisi quis voluptas non aut quas.
      duration: 6887616300691749277
      role: Pariatur et.
    required:
    - company
    - role
    - duration
  ResumeRequestBody:
    title: ResumeRequestBody
    type: object
    properties:
      education:
        type: array
        items:
          $ref: '#/definitions/EducationRequestBody'
        description: Education section in the resume
        example:
        - institution: Qui ut voluptates libero consectetur in.
          major: Aliquid nesciunt harum exercitationem qui reprehenderit.
        - institution: Qui ut voluptates libero consectetur in.
          major: Aliquid nesciunt harum exercitationem qui reprehenderit.
      experience:
        type: array
        items:
          $ref: '#/definitions/ExperienceRequestBody'
        description: Experience section in the resume
        example:
        - company: Consectetur ut.
          duration: 9021502551841493030
          role: Pariatur ad accusantium.
        - company: Consectetur ut.
          duration: 9021502551841493030
          role: Pariatur ad accusantium.
      name:
        type: string
        description: Name in the resume
        example: Dolorem quae voluptatum ex at doloribus assumenda.
    example:
      education:
      - institution: Qui ut voluptates libero consectetur in.
        major: Aliquid nesciunt harum exercitationem qui reprehenderit.
      - institution: Qui ut voluptates libero consectetur in.
        major: Aliquid nesciunt harum exercitationem qui reprehenderit.
      experience:
      - company: Consectetur ut.
        duration: 9021502551841493030
        role: Pariatur ad accusantium.
      - company: Consectetur ut.
        duration: 9021502551841493030
        role: Pariatur ad accusantium.
      - company: Consectetur ut.
        duration: 9021502551841493030
        role: Pariatur ad accusantium.
      - company: Consectetur ut.
        duration: 9021502551841493030
        role: Pariatur ad accusantium.
      name: Exercitationem non minima.
    required:
    - name
  ResumeStoredResumeResponseCollection:
    title: 'Mediatype identifier: application/vnd.goa.resume; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/StoredResumeResponse'
    description: ListResponseBody is the result type for an array of StoredResumeResponse
      (default view)
    example:
    - created_at: Tempore quidem animi nihil.
      education:
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      experience:
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      id: 47036700361575944
      name: Assumenda sed.
    - created_at: Tempore quidem animi nihil.
      education:
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      experience:
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      id: 47036700361575944
      name: Assumenda sed.
    - created_at: Tempore quidem animi nihil.
      education:
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      experience:
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      id: 47036700361575944
      name: Assumenda sed.
    - created_at: Tempore quidem animi nihil.
      education:
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      experience:
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      id: 47036700361575944
      name: Assumenda sed.
  StoredResumeResponse:
    title: 'Mediatype identifier: application/vnd.goa.resume; view=default'
    type: object
    properties:
      created_at:
        type: string
        description: Time when resume was created
        example: Est ut aut doloribus et eveniet autem.
      education:
        type: array
        items:
          $ref: '#/definitions/EducationResponse'
        description: Education section in the resume
        example:
        - institution: Mollitia dolores sequi sed veritatis totam omnis.
          major: Repellendus et et aut sint.
        - institution: Mollitia dolores sequi sed veritatis totam omnis.
          major: Repellendus et et aut sint.
        - institution: Mollitia dolores sequi sed veritatis totam omnis.
          major: Repellendus et et aut sint.
        - institution: Mollitia dolores sequi sed veritatis totam omnis.
          major: Repellendus et et aut sint.
      experience:
        type: array
        items:
          $ref: '#/definitions/ExperienceResponse'
        description: Experience section in the resume
        example:
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
      id:
        type: integer
        description: ID of the resume
        example: 8198932393410705726
        format: int64
      name:
        type: string
        description: Name in the resume
        example: Quae sunt aut qui corporis molestiae.
    description: StoredResumeResponse result type (default view)
    example:
      created_at: Voluptate quam.
      education:
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      - institution: Mollitia dolores sequi sed veritatis totam omnis.
        major: Repellendus et et aut sint.
      experience:
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      - company: Aut rem.
        duration: 5176619058752078184
        role: Consequuntur quam est commodi cumque eaque quisquam.
      id: 3919877609510640762
      name: Perspiciatis at.
    required:
    - id
    - name
    - experience
    - education
    - created_at
