package design

import (
	"regexp"

	"goa.design/goa.v2/design"
	"goa.design/goa.v2/eval"
)

var (
	// Root holds the root expression built on process initialization.
	Root = &RootExpr{}

	// WildcardRegex is the regular expression used to capture path parameters.
	WildcardRegex = regexp.MustCompile(`/(?::|\*)([a-zA-Z0-9_]+)`)

	// ErrorMedia is the built-in media type for error responses.
	ErrorMedia = design.ErrorMedia
)

const (
	// DefaultView is the name of the default view.
	DefaultView = "default"
)

type (
	// ParamHolder is the interface implemented by the design data structures
	// that represent HTTP constructs with path and query string parameters.
	ParamHolder interface {
		eval.Expression
		// Params returns the attribute holding the parameters. It takes
		// care of initializing the underlying struct field so that it
		// never returns nil.
		Params() *design.AttributeExpr
	}

	// HeaderHolder is the interface implemented by the design data
	// structures that represent HTTP constructs with HTTP headers.
	HeaderHolder interface {
		eval.Expression
		// Headers returns the attribute holding the headers. It takes
		// care of initializing the underlying struct field so that it
		// never returns nil.
		Headers() *design.AttributeExpr
	}

	// RootExpr is the data structure built by the top level HTTP DSL.
	RootExpr struct {
		// Path is the common request path prefix to all the service
		// HTTP endpoints.
		Path string
		// Consumes lists the mime types supported by the API controllers
		Consumes []*EncodingExpr
		// Produces lists the mime types generated by the API controllers
		Produces []*EncodingExpr
		// Resources contains the resources created by the DSL.
		Resources []*ResourceExpr
		// HTTPErrors lists the error HTTP responses.
		HTTPErrors []*HTTPErrorExpr
		// Params defines common request parameters to all the service
		// HTTP endpoints.
		params *design.AttributeExpr
		// Headers defines common headers to all the service HTTP
		// endpoints.
		headers *design.AttributeExpr
	}
)

// EvalName is the expression name used by the evaluation engine to display
// error messages.
func (r *RootExpr) EvalName() string {
	return "API HTTP"
}

// Resource returns the resource with the given name if any.
func (r *RootExpr) Resource(name string) *ResourceExpr {
	for _, res := range r.Resources {
		if res.Name == name {
			return res
		}
	}
	return nil
}

// ResourceFor creates a new or returns the existing resource definition for the
// given service.
func (r *RootExpr) ResourceFor(s *design.ServiceExpr) *ResourceExpr {
	if res := r.Resource(s.Name); res != nil {
		return res
	}
	res := &ResourceExpr{
		ServiceExpr: s,
		Actions:     make([]*ActionExpr, len(s.Endpoints)),
	}
	for i, e := range s.Endpoints {
		res.Actions[i] = &ActionExpr{
			EndpointExpr: e,
			Resource:     res,
		}
	}
	r.Resources = append(r.Resources, res)
	return res
}

// Headers initializes and returns the attribute holding the API headers.
func (r *RootExpr) Headers() *design.AttributeExpr {
	if r.headers == nil {
		r.headers = &design.AttributeExpr{Type: make(design.Object)}
	}
	return r.headers
}

// Params initializes and returns the attribute holding the API parameters.
func (r *RootExpr) Params() *design.AttributeExpr {
	if r.params == nil {
		r.params = &design.AttributeExpr{Type: make(design.Object)}
	}
	return r.params
}

// ExtractWildcards returns the names of the wildcards that appear in path.
func ExtractWildcards(path string) []string {
	matches := WildcardRegex.FindAllStringSubmatch(path, -1)
	wcs := make([]string, len(matches))
	for i, m := range matches {
		wcs[i] = m[1]
	}
	return wcs
}
