// This file checks that WebSocket response collections keep the public Go
// names generated by released Goa versions.
package codegen

import (
	"testing"

	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/codegen/testutil"
	"goa.design/goa/v3/expr"
	"goa.design/goa/v3/http/codegen/testdata"
)

// TestReleasedStreamingResponseCollectionNames catches renaming a response
// collection merely because it is sent after receiving streamed input.
func TestReleasedStreamingResponseCollectionNames(t *testing.T) {
	root := expr.RunDSL(t, testdata.StreamingPayloadResultCollectionWithExplicitViewDSL)
	plan := linkedHTTPPlanForRoot(t, root)

	t.Run("server", func(t *testing.T) {
		file := plan.ServerTypeFiles()[0]
		sections := append(file.Section("response-server-body"), file.Section("server-body-init")...)
		code := codegen.SectionsCode(t, sections)
		testutil.AssertGo(t, "testdata/golden/released_streaming_response_collection_server.go.golden", code)
	})

	t.Run("client", func(t *testing.T) {
		file := plan.ClientTypeFiles()[0]
		sections := append(file.Section("client-response-body"), file.Section("client-body-init")...)
		code := codegen.SectionsCode(t, sections)
		testutil.AssertGo(t, "testdata/golden/released_streaming_response_collection_client.go.golden", code)
	})
}
