package codegen

import (
	"fmt"

	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/expr"
)

// protoBufTransform produces Go code to initialize a data structure defined
// by target from an instance of data structure defined by source. The source
// or target is a protocol buffer type. The transformation is generated by the
// shared transform engine specialized via the protocol buffer transform hooks
// (see protoHooks).
//
// source, target are the source and target attributes used in transformation
//
// sourceVar, targetVar are the source and target variables
//
// sourceCtx, targetCtx are the source and target attribute contexts
//
// `proto` param if true indicates that the target is a protocol buffer type
//
// newVar if true initializes a target variable with the generated Go code
// using `:=` operator. If false, it assigns Go code to the target variable
// using `=`.
func protoBufTransform(source, target *expr.AttributeExpr, sourceVar, targetVar string, sourceCtx, targetCtx *codegen.AttributeContext, proto, newVar bool) (string, []*codegen.TransformFunctionData, error) {
	prefix := "protobuf"
	if proto {
		target = expr.DupAtt(target)
		removeMeta(target)
		prefix = "svc"
	} else {
		source = expr.DupAtt(source)
		removeMeta(source)
	}
	ta := &codegen.TransformAttrs{
		SourceCtx: sourceCtx,
		TargetCtx: targetCtx,
		Prefix:    prefix,
		Hooks:     protoHooks(proto, targetCtx),
	}
	return codegen.GoTransformWithAttrs(source, target, sourceVar, targetVar, ta, newVar)
}

// removeMeta removes meta attributes from the given attribute that cannot be
// honored. This is needed to make sure that any field name overridding is
// removed when generating protobuf types (as protogen itself won't honor these
// overrides).
func removeMeta(att *expr.AttributeExpr) {
	_ = codegen.Walk(att, func(a *expr.AttributeExpr) error {
		delete(a.Meta, "struct:field:name")
		delete(a.Meta, "struct:field:external")
		delete(a.Meta, "struct.field.external") // Deprecated syntax. Only present for backward compatibility.
		return nil
	})
}

// convertType produces code to initialize a target type from a source type
// held by srcVar. proto is true when the transformation initializes a
// protocol buffer type.
// NOTE: For Int and UInt kinds, protocol buffer Go compiler generates
// int32 and uint32 respectively whereas Goa generates int and uint.
func convertType(src, tgt *expr.AttributeExpr, srcPtr, tgtPtr bool, srcVar string, proto bool, ta *codegen.TransformAttrs) string {
	if expr.IsAlias(src.Type) || expr.IsAlias(tgt.Type) {
		srcp, tgtp := unAlias(src), unAlias(tgt)
		if srcp.Type == tgtp.Type {
			if proto {
				return convertPrimitiveToProto(src, tgtp, srcPtr, tgtPtr, srcVar)
			}
			return convertPrimitiveFromProto(srcp, tgt, srcPtr, tgtPtr, srcVar, ta)
		}
		return fmt.Sprintf("%s(%s)", codegen.TransformHelperName(src, tgt, ta), srcVar)
	}

	if _, ok := src.Type.(expr.UserType); ok {
		return fmt.Sprintf("%s(%s)", codegen.TransformHelperName(src, tgt, ta), srcVar)
	}

	srcType, _ := codegen.GetMetaType(src)
	tgtType, _ := codegen.GetMetaType(tgt)
	if srcType == "" && tgtType == "" && (src.Type != expr.Int) && (src.Type != expr.UInt) && (src.Type != expr.Any) {
		// Nothing to do, except for Any type which needs special conversion
		return srcVar
	}

	if proto {
		return convertPrimitiveToProto(src, tgt, srcPtr, tgtPtr, srcVar)
	}
	return convertPrimitiveFromProto(src, tgt, srcPtr, tgtPtr, srcVar, ta)
}

const convertGoAnyToProtobufValueFunc = `func() *structpb.Value {
	// Convert Go any to protobuf Value directly
	if %s == nil {
		return structpb.NewNullValue()
	}
	value, err := structpb.NewValue(%s)
	if err != nil {
		panic(fmt.Sprintf("failed to convert value to structpb.Value: %%v", err))
	}
	return value
}()`

const convertProtobufValueToGoAnyFunc = `func() any {
	// Convert protobuf Value to Go any directly
	if %s != nil {
		return %s.AsInterface()
	}
	return nil
}()`

// convertPrimitiveToProto returns the code to convert a primitive type to its
// protocol buffer representation.
func convertPrimitiveToProto(_, tgt *expr.AttributeExpr, srcPtr, _ bool, srcVar string) string {
	// Special handling for Any type conversion to google.protobuf.Value
	if tgt.Type.Kind() == expr.AnyKind {
		if srcPtr {
			srcVar = "*" + srcVar
		}

		return fmt.Sprintf(convertGoAnyToProtobufValueFunc, srcVar, srcVar)
	}

	tgtType := protoBufNativeGoTypeName(tgt.Type)
	if srcPtr {
		srcVar = "*" + srcVar
	}
	return fmt.Sprintf("%s(%s)", tgtType, srcVar)
}

// convertPrimitiveFromProto returns the code to convert the protocol buffer
// representation of a primitive type back to the service type.
func convertPrimitiveFromProto(_, tgt *expr.AttributeExpr, srcPtr, _ bool, srcVar string, ta *codegen.TransformAttrs) string {
	// Special handling for Any type conversion from google.protobuf.Value
	if tgt.Type.Kind() == expr.AnyKind {
		if srcPtr {
			srcVar = "*" + srcVar
		}

		return fmt.Sprintf(convertProtobufValueToGoAnyFunc, srcVar, srcVar)
	}

	tgtType, _ := codegen.GetMetaType(tgt)
	if tgtType == "" {
		tgtType = ta.TargetCtx.Scope.Ref(tgt, ta.TargetCtx.Pkg(tgt))
	}
	if srcPtr {
		srcVar = "*" + srcVar
	}
	return fmt.Sprintf("%s(%s)", tgtType, srcVar)
}

// protocOneofWrapperRef returns the reference to the Go wrapper type that
// protoc generates for a oneof field: it mirrors protoc generated Go oneof
// wrapper type naming which joins the parent message type name and the oneof
// field name with an underscore (Message_Field).
func protocOneofWrapperRef(message, fieldName string) string {
	return message + "_" + fieldName
}
