// This file compares Goa's protobuf Go names with code generated by the
// supported protobuf tools.
package codegen

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

// TestProtocNameVersion rejects a name version that Goa does not support.
func TestProtocNameVersion(t *testing.T) {
	_, err := newProtocNameRules("unknown")
	require.EqualError(t, err, `unsupported protobuf Go naming version "unknown"`)
}

// TestProtocDeclarationFamilies checks every generated name family that Goa
// uses in its gRPC client and server code.
func TestProtocDeclarationFamilies(t *testing.T) {
	descriptor, declarations := generateProtocNameFixture(t)
	rules, err := newProtocNameRules(protocNameVersionGo1_36GRPC1_6)
	require.NoError(t, err)
	names, err := rules.file(descriptor)
	require.NoError(t, err)

	tests := []struct {
		descriptor string
		role       protocNameRole
		want       string
	}{
		{"goa.names.v1.api2_http_request", protocMessageName, "Api2HttpRequest"},
		{"goa.names.v1.api2_http_request.nested_api2", protocMessageName, "Api2HttpRequestNestedApi2"},
		{"goa.names.v1.wrapper_conflict._BranchValue", protocMessageName, "WrapperConflict_XBranchValue"},
		{"goa.names.v1.Explicit_HTTP2_Name", protocMessageName, "Explicit_HTTP2_Name"},
		{"goa.names.v1.api2_http_request.api_url", protocFieldName, "ApiUrl"},
		{"goa.names.v1.api2_http_request.api2_url", protocFieldName, "Api2Url"},
		{"goa.names.v1.api2_http_request.dns_2_server", protocFieldName, "Dns_2Server"},
		{"goa.names.v1.api2_http_request.x509_cert", protocFieldName, "X509Cert"},
		{"goa.names.v1.api2_http_request.reset", protocFieldName, "Reset_"},
		{"goa.names.v1.api2_http_request.string", protocFieldName, "String_"},
		{"goa.names.v1.api2_http_request.proto_message", protocFieldName, "ProtoMessage_"},
		{"goa.names.v1.api2_http_request.descriptor", protocFieldName, "Descriptor_"},
		{"goa.names.v1.Explicit_HTTP2_Name.Explicit_Field2_Name", protocFieldName, "Explicit_Field2_Name"},
		{"goa.names.v1.http_2_status", protocEnumName, "Http_2Status"},
		{"goa.names.v1.HTTP_2_STATUS_UNSPECIFIED", protocEnumValueName, "Http_2Status_HTTP_2_STATUS_UNSPECIFIED"},
		{"goa.names.v1.HTTP2_OK", protocEnumValueName, "Http_2Status_HTTP2_OK"},
		{"goa.names.v1.api2_http_request.nested_api2.state_2", protocEnumName, "Api2HttpRequestNestedApi2State_2"},
		{"goa.names.v1.api2_http_request.nested_api2.DNS2_READY", protocEnumValueName, "Api2HttpRequestNestedApi2_DNS2_READY"},
		{"goa.names.v1.api2_http_request.result_2_kind", protocOneofFieldName, "Result_2Kind"},
		{"goa.names.v1.api2_http_request.result_2_kind", protocOneofInterfaceName, "isApi2HttpRequest_Result_2Kind"},
		{"goa.names.v1.api2_http_request.http_2xx", protocOneofWrapperName, "Api2HttpRequest_Http_2Xx"},
		{"goa.names.v1.api2_http_request.api_url_value", protocOneofWrapperName, "Api2HttpRequest_ApiUrlValue"},
		{"goa.names.v1.wrapper_conflict.choiceValue", protocOneofFieldName, "ChoiceValue_"},
		{"goa.names.v1.wrapper_conflict.choiceValue", protocOneofInterfaceName, "isWrapperConflict_ChoiceValue_"},
		{"goa.names.v1.wrapper_conflict.branchValue", protocOneofWrapperName, "WrapperConflict_BranchValue"},
		{"goa.names.v1.wrapper_conflict.reset", protocOneofWrapperName, "WrapperConflict_Reset_"},
		{"goa.names.v1.api2_http_service", protocServiceClientName, "Api2HttpServiceClient"},
		{"goa.names.v1.api2_http_service", protocServiceClientStructName, "api2HttpServiceClient"},
		{"goa.names.v1.api2_http_service", protocServiceClientConstructorName, "NewApi2HttpServiceClient"},
		{"goa.names.v1.api2_http_service", protocServiceServerName, "Api2HttpServiceServer"},
		{"goa.names.v1.api2_http_service", protocServiceUnimplementedServerName, "UnimplementedApi2HttpServiceServer"},
		{"goa.names.v1.api2_http_service", protocServiceUnsafeServerName, "UnsafeApi2HttpServiceServer"},
		{"goa.names.v1.api2_http_service", protocServiceRegisterName, "RegisterApi2HttpServiceServer"},
		{"goa.names.v1.api2_http_service", protocServiceDescriptorName, "Api2HttpService_ServiceDesc"},
		{"goa.names.v1.api2_http_service.get_url2", protocMethodName, "GetUrl2"},
		{"goa.names.v1.api2_http_service.get_url2", protocMethodFullName, "Api2HttpService_GetUrl2_FullMethodName"},
		{"goa.names.v1.api2_http_service.get_url2", protocMethodHandlerName, "_Api2HttpService_GetUrl2_Handler"},
		{"goa.names.v1.api2_http_service.watch_dns2", protocMethodClientStreamName, "Api2HttpService_WatchDns2Client"},
		{"goa.names.v1.api2_http_service.watch_dns2", protocMethodServerStreamName, "Api2HttpService_WatchDns2Server"},
		{"goa.names.v1.api2_http_service.upload_api2", protocMethodClientStreamName, "Api2HttpService_UploadApi2Client"},
		{"goa.names.v1.api2_http_service.upload_api2", protocMethodServerStreamName, "Api2HttpService_UploadApi2Server"},
		{"goa.names.v1.api2_http_service.sync_x509", protocMethodClientStreamName, "Api2HttpService_SyncX509Client"},
		{"goa.names.v1.api2_http_service.sync_x509", protocMethodServerStreamName, "Api2HttpService_SyncX509Server"},
	}

	for _, test := range tests {
		t.Run(test.descriptor+"/"+test.role.String(), func(t *testing.T) {
			got, ok := names.lookup(test.descriptor, test.role)
			require.True(t, ok, "name was not recorded")
			require.Equal(t, test.want, got)
			require.Contains(t, declarations, got, "the supported tools did not declare the predicted Go name")
		})
	}
}

// generateProtocNameFixture runs the supported tools and returns their input
// description and every Go name declared in their output.
func generateProtocNameFixture(t *testing.T) (*descriptorpb.FileDescriptorProto, map[string]struct{}) {
	t.Helper()
	directory := t.TempDir()
	source, err := os.ReadFile(filepath.Join("testdata", "protoc_names.proto"))
	require.NoError(t, err)
	protoPath := filepath.Join(directory, "protoc_names.proto")
	require.NoError(t, os.WriteFile(protoPath, source, 0o600))
	require.NoError(t, protoc(defaultProtocCmd, protoPath))

	descriptorPath := filepath.Join(directory, "descriptor.pb")
	args := defaultProtocCmd[1:len(defaultProtocCmd):len(defaultProtocCmd)]
	args = append(args,
		"--proto_path", directory,
		"--descriptor_set_out", descriptorPath,
		protoPath,
	)
	output, err := exec.Command(defaultProtocCmd[0], args...).CombinedOutput()
	require.NoError(t, err, string(output))

	encoded, err := os.ReadFile(descriptorPath)
	require.NoError(t, err)
	return readProtocDescriptor(t, encoded), declaredGoNames(
		t,
		filepath.Join(directory, "protoc_names.pb.go"),
		filepath.Join(directory, "protoc_names_grpc.pb.go"),
	)
}

// readProtocDescriptorRequest converts a descriptor set into the request read
// by protobuf's public Go name code.
func readProtocDescriptor(t *testing.T, encoded []byte) *descriptorpb.FileDescriptorProto {
	t.Helper()
	set := &descriptorpb.FileDescriptorSet{}
	require.NoError(t, proto.Unmarshal(encoded, set))
	require.Len(t, set.File, 1)
	return set.File[0]
}

// declaredGoNames returns package names, fields, and receiver methods declared
// by the generated files.
func declaredGoNames(t *testing.T, paths ...string) map[string]struct{} {
	t.Helper()
	result := make(map[string]struct{})
	for _, path := range paths {
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		require.NoError(t, err)
		for _, declaration := range file.Decls {
			switch declaration := declaration.(type) {
			case *ast.GenDecl:
				for _, specification := range declaration.Specs {
					switch specification := specification.(type) {
					case *ast.TypeSpec:
						result[specification.Name.Name] = struct{}{}
						ast.Inspect(specification.Type, func(node ast.Node) bool {
							field, ok := node.(*ast.Field)
							if ok {
								for _, name := range field.Names {
									result[name.Name] = struct{}{}
								}
							}
							return true
						})
					case *ast.ValueSpec:
						for _, name := range specification.Names {
							result[name.Name] = struct{}{}
						}
					}
				}
			case *ast.FuncDecl:
				result[declaration.Name.Name] = struct{}{}
			}
		}
	}
	return result
}
