// This file analyzes gRPC endpoint designs into the immutable data consumed by
// protobuf message, client, server, conversion, and validation templates.
package codegen

import (
	"fmt"
	"path"
	"strings"

	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/codegen/service"
	"goa.design/goa/v3/expr"
)

type (
	// ServicesData contains the data computed from the gRPC service expressions
	// indexed by service name.
	ServicesData struct {
		*service.ServicesData
		GRPCServices map[string]*ServiceData
		cliPlan      *grpcCLIPlan
	}

	// ServiceData contains the data used to render the code related to a
	// single service.
	ServiceData struct {
		// Service contains the related service data.
		Service *service.Data
		// ClientPkgName is the frozen qualifier for the generated gRPC client
		// package.
		ClientPkgName string
		// ServerPkgName is the frozen qualifier for the generated gRPC server
		// package.
		ServerPkgName string
		// PkgName is the name of the generated package in *.pb.go.
		PkgName string
		// ProtoImports is the list of proto package imports.
		ProtoImports []string
		// Name is the service name.
		Name string
		// Description is the service description.
		Description string
		// Endpoints describes the gRPC service endpoints.
		Endpoints []*EndpointData
		// Messages describes the message data for this service.
		Messages []*service.UserTypeData
		// ServerStruct is the name of the gRPC server struct.
		ServerStruct string
		// ClientStruct is the name of the gRPC client struct,
		ClientStruct string
		// ServerInit is the name of the constructor of the server struct.
		ServerInit string
		// ClientInit is the name of the constructor of the client struct.
		ClientInit string
		// ServerInterface is the name of the gRPC server interface implemented
		// by the service.
		ServerInterface string
		// ClientInterface is the name of the gRPC client interface implemented
		// by the service.
		ClientInterface string
		// ClientInterfaceInit is the name of the client constructor function in
		// the generated pb.go package.
		ClientInterfaceInit string
		// Scope is the name scope for protocol buffers
		Scope *codegen.NameScope

		// protobuf owns declarations emitted in this service's actual protobuf
		// output package.
		protobuf *protobufPackageCatalog

		// transformHelpers is the list of transform functions required by the
		// constructors.
		transformHelpers []*codegen.TransformFunctionData
		// validations contain the data to generate the validation functions to
		// validate the initialized type.
		validations []*ValidationData
	}

	// EndpointData contains the data used to render the code related to
	// gRPC endpoint.
	EndpointData struct {
		// ServiceName is the name of the service.
		ServiceName string
		// PkgName is the name of the generated package in *.pb.go.
		PkgName string
		// ServicePkgName is the name of the service package name.
		ServicePkgName string
		// Method is the data for the underlying method expression.
		Method *service.MethodData
		// PayloadType is the type of the payload.
		PayloadType expr.DataType
		// PayloadRef is the fully qualified reference to the method payload.
		PayloadRef string
		// ResultRef is the fully qualified reference to the method result.
		ResultRef string
		// ViewedResultRef is the fully qualified reference to the viewed result.
		ViewedResultRef string
		// Request is the gRPC request data.
		Request *RequestData
		// Response is the gRPC response data.
		Response *ResponseData
		// MetadataSchemes lists all the security requirement schemes that
		// apply to the method and are encoded in the request metadata.
		MetadataSchemes service.SchemesData
		// MessageSchemes lists all the security requirement schemes that
		// apply to the method and are encoded in the request message.
		MessageSchemes service.SchemesData
		// Errors describes the method gRPC errors.
		Errors []*ErrorData

		// server side

		// ServerStruct is the name of the gRPC server struct.
		ServerStruct string
		// ServerInterface is the name of the gRPC server interface implemented
		// by the service.
		ServerInterface string
		// ServerStream is the server stream data.
		ServerStream *StreamData

		// client side

		// ClientMethodName is the name of the gRPC method generated by protoc-gen-go.
		ClientMethodName string
		// ClientStruct is the name of the gRPC client struct,
		ClientStruct string
		// ClientInterface is the name of the gRPC client interface implemented
		// by the service.
		ClientInterface string
		// ClientStream is the client stream data.
		ClientStream *StreamData
	}

	// MetadataData describes a gRPC metadata field.
	MetadataData struct {
		// Name is the name of the metadata key.
		Name string
		// AttributeName is the name of the corresponding attribute.
		AttributeName string
		// Description is the metadata description.
		Description string
		// FieldName is the name of the struct field that holds the
		// metadata value if any, empty string otherwise.
		FieldName string
		// FieldType is the type of the struct field.
		FieldType expr.DataType
		// ServiceAttribute is the service field populated from this metadata.
		ServiceAttribute *expr.AttributeExpr
		// WireAttribute is the detached native gRPC metadata value.
		WireAttribute *expr.AttributeExpr
		// VarName is the name of the Go variable used to read or
		// convert the metadata value.
		VarName string
		// WireVarName is the local variable produced before metadata encoding.
		WireVarName string
		// EncodeCode converts the service field to WireVarName.
		EncodeCode string
		// DecodeCode converts VarName to the service constructor target. The
		// constructor replaces metadataTargetPlaceholder with its result variable.
		DecodeCode string
		// TypeName is the name of the type.
		TypeName string
		// TypeRef is the reference to the type.
		TypeRef string
		// Required is true if the metadata is required.
		Required bool
		// Pointer is true if and only the metadata variable is a pointer.
		Pointer bool
		// StringSlice is true if the metadata value type is array of strings.
		StringSlice bool
		// Slice is true if the metadata value type is an array.
		Slice bool
		// Type describes the datatype of the variable value. Mainly
		// used for conversion.
		Type expr.DataType
		// Validate contains the validation code if any.
		Validate string
		// DefaultValue contains the default value if any.
		DefaultValue any
		// Example is an example value.
		Example any
	}

	// ErrorData contains the error information required to generate the
	// transport decode (client) and encode (server) code.
	ErrorData struct {
		// StatusCode is the response gRPC status code.
		StatusCode string
		// Name is the error name.
		Name string
		// Ref is a reference to the error type.
		Ref string
		// Response is the error response data.
		Response *ResponseData
	}

	// RequestData describes a gRPC request.
	RequestData struct {
		// Description is the request description.
		Description string
		// Message is the gRPC request message used by the transport. For
		// streaming payload methods with an initial payload frame, this is the
		// synthesized stream envelope.
		Message *service.UserTypeData
		// PayloadMessage is the gRPC message that carries the one-shot method
		// payload fields before any stream envelope wrapping.
		PayloadMessage *service.UserTypeData
		// StreamEnvelope describes the synthesized stream envelope when the
		// transport must carry both the one-shot payload and streaming payload
		// items through the same streamed protobuf message.
		StreamEnvelope *StreamEnvelopeData
		// LegacyDecode describes the server-side decoding of requests sent by
		// clients that speak the legacy stream protocol which predates the
		// stream envelope and carries the one-shot method payload in gRPC
		// request metadata. It is nil unless the endpoint enables the
		// "grpc:stream:compat" meta.
		LegacyDecode *LegacyDecodeData
		// Metadata is the request metadata.
		Metadata []*MetadataData
		// ServerConvert is the request data with constructor function to
		// initialize the method payload type from the generated payload type in
		// *.pb.go.
		ServerConvert *ConvertData
		// ClientConvert is the request data with constructor function to
		// initialize the generated payload type in *.pb.go from the
		// method payload.
		ClientConvert *ConvertData
		// CLIArgs is the list of arguments for the command-line client.
		// This is set only for the client side.
		CLIArgs []*InitArgData
	}

	// StreamEnvelopeData describes a synthesized streamed protobuf envelope.
	StreamEnvelopeData struct {
		// FieldName is the protobuf oneof field name on the envelope message.
		FieldName string
		// InitialFieldName is the name of the initial payload branch field.
		InitialFieldName string
		// InitialWrapperRef is the fully qualified protobuf wrapper type for the
		// initial payload branch.
		InitialWrapperRef string
		// StreamItemFieldName is the name of the streaming payload item branch
		// field.
		StreamItemFieldName string
		// StreamItemWrapperRef is the fully qualified protobuf wrapper type for
		// the streaming payload item branch.
		StreamItemWrapperRef string
	}

	// LegacyDecodeData describes how generated servers decode the one-shot
	// method payload that legacy stream protocol clients send in gRPC
	// request metadata.
	LegacyDecodeData struct {
		// FuncName is the name of the generated legacy request decoder.
		FuncName string
		// Metadata lists the request metadata carrying the method payload
		// along with any explicitly mapped and security metadata.
		Metadata []*MetadataData
		// ServerConvert builds the method payload from the metadata values.
		// It is nil when the payload is not an object type, in which case it
		// travels under the reserved "goa_payload" metadata key and maps
		// directly to the payload.
		ServerConvert *ConvertData
	}

	// ResponseData describes a gRPC success or error response.
	ResponseData struct {
		// StatusCode is the return code of the response.
		StatusCode string
		// Description is the response description.
		Description string
		// Message is the gRPC response message.
		Message *service.UserTypeData
		// Headers is the response header metadata.
		Headers []*MetadataData
		// Trailers is the response trailer metadata.
		Trailers []*MetadataData
		// ServerConvert is the type data with constructor function to
		// initialize the generated response type in *.pb.go from the
		// method result type or the projected result type.
		ServerConvert *ConvertData
		// ClientConvert is the type data with constructor function to
		// initialize the method result type or the projected result type
		// from the generated response type in *.pb.go.
		ClientConvert *ConvertData
	}

	// ConvertData contains the data to convert source type to a target type.
	// For request type, it contains data to transform gRPC request type to the
	// corresponding payload type (server) and vice versa (client).
	// For response type, it contains data to transform gRPC response type to the
	// corresponding result type (client) and vice versa (server).
	ConvertData struct {
		// SrcName is the fully qualified name of the source type.
		SrcName string
		// SrcRef is the fully qualified reference to the source type.
		SrcRef string
		// TgtName is the fully qualified name of the target type.
		TgtName string
		// TgtRef is the fully qualified reference to the target type.
		TgtRef string
		// Inits contain the data required to render the constructor if any
		// to transform the source type to a target type. If the source or target
		// type is a goa result type, we generate one constructor for every view
		// defined in the result type.
		Init *InitData
		// Validation contains the data required to render the validation function
		// to validate the initialized type.
		Validation *ValidationData
	}

	// ValidationData contains the data necessary to render the validation
	// function.
	ValidationData struct {
		// Name is the validation function name.
		Name string
		// Def is the validation function definition.
		Def string
		// VarName is the name of the argument.
		ArgName string
		// SrcName is the fully qualified name of the type being validated.
		SrcName string
		// SrcRef is the fully qualified reference to the type being validated.
		SrcRef string
		// Kind indicates that the validation is for request (server-side),
		// response (client-side), or both (server and client side) messages.
		// It is used to generate validation code in the server and client packages.
		Kind validateKind
	}

	// InitData contains the data required to render a constructor.
	InitData struct {
		// Name is the constructor function name.
		Name string
		// Description is the function description.
		Description string
		// Args is the list of constructor arguments.
		Args []*InitArgData
		// ReturnVarName is the name of the variable to be returned.
		ReturnVarName string
		// ReturnTypeRef is the qualified (including the package name)
		// reference to the return type.
		ReturnTypeRef string
		// ReturnTypePkg is the package where the return type is present.
		ReturnTypePkg string
		// ReturnIsStruct is true if the return type is a struct.
		ReturnIsStruct bool
		// Code is the transformation code.
		Code string
	}

	// InitArgData represents a single constructor argument.
	InitArgData struct {
		// Name is the argument name.
		Name string
		// Description is the argument description.
		Description string
		// Reference to the argument, e.g. "&body".
		Ref string
		// FieldName is the name of the data structure field that should
		// be initialized with the argument if any.
		FieldName string
		// FieldType is the type of the data structure field that should be
		// initialized with the argument if any.
		FieldType expr.DataType
		// InitCode converts and assigns this argument to the constructor result.
		InitCode string
		// TypeName is the argument type name.
		TypeName string
		// TypeRef is the argument type reference.
		TypeRef string
		// Type is the argument type. It is never an aliased user type.
		Type expr.DataType
		// Pointer is true if a pointer to the arg should be used.
		Pointer bool
		// Required is true if the arg is required to build the payload.
		Required bool
		// DefaultValue is the default value of the arg.
		DefaultValue any
		// Validate contains the validation code for the argument
		// value if any.
		Validate string
		// Example is a example value
		Example any
	}

	// StreamData contains data to render the stream struct type that implements
	// the service stream interface.
	StreamData struct {
		// VarName is the name of the struct type.
		VarName string
		// Type is the stream type (client or server).
		Type string
		// ServiceInterface is the service interface that the struct implements.
		ServiceInterface string
		// Interface is the stream interface in *.pb.go stored in the struct.
		Interface string
		// Endpoint is the streaming endpoint data.
		Endpoint *EndpointData
		// SendName is the name of the send function.
		SendName string
		// SendDesc is the description for the send function.
		SendDesc string
		// SendWithContextName is the name of the send function with context.
		SendWithContextName string
		// SendWithContextDesc is the description for the send function with context.
		SendWithContextDesc string
		// SendRef is the fully	qualified reference to the type sent across the
		// stream.
		SendRef string
		// SendConvert is the type sent through the stream. It contains the
		// constructor to convert the service send type to the type expected by
		// the gRPC send type (in *.pb.go)
		SendConvert *ConvertData
		// RecvConvert is the type received through the stream. It contains the
		// constructor to convert the gRPC type (in *.pb.go) to the service receive
		// type.
		RecvConvert *ConvertData
		// RecvName is the name of the receive function.
		RecvName string
		// RecvDesc is the description for the recv function.
		RecvDesc string
		// RecvWithContextName is the name of the receive function with context.
		RecvWithContextName string
		// RecvWithContextDesc is the description for the recv function with context.
		RecvWithContextDesc string
		// RecvRef is the fully	qualified reference to the type received from the
		// stream.
		RecvRef string
		// MustClose indicates whether to generate the Close() function
		// for the stream.
		MustClose bool
	}

	// validateKind is a type to determine where the validation code is generated
	// (server, client, or both)
	validateKind int
)

const (
	// pbPkgName is the directory name where the .proto file is generated and
	// compiled.
	pbPkgName = "pb"
	// metadataTargetPlaceholder marks the constructor result until the same
	// metadata record is attached to its concrete conversion function.
	metadataTargetPlaceholder = "__goa_metadata_target__"
	// validateServer generates the validation code for request messages in the
	// server package.
	validateServer validateKind = iota + 1
	// validateClient generates the validation code for response messages in the
	// client package.
	validateClient
)

// newServicesData creates the render data owned by one retained gRPC plan.
func newServicesData(services *service.ServicesData, plan *Plan) *ServicesData {
	if services.Root != plan.root {
		panic(fmt.Sprintf("gRPC service data does not belong to design %q", plan.root.API.Name))
	}
	return &ServicesData{
		ServicesData: services,
		GRPCServices: make(map[string]*ServiceData),
		cliPlan:      plan.cli,
	}
}

// Get retrieves the transport data for the service with the given name
// computing it if needed. It returns nil if there is no service with the given
// name.
func (d *ServicesData) Get(name string) *ServiceData {
	if data, ok := d.GRPCServices[name]; ok {
		return data
	}
	service := d.Root.API.GRPC.Service(name)
	if service == nil {
		return nil
	}
	d.GRPCServices[name] = d.analyze(service)
	return d.GRPCServices[name]
}

// Endpoint returns the endpoint data for the endpoint with the given name, nil
// if there isn't one.
func (sd *ServiceData) Endpoint(name string) *EndpointData {
	for _, ed := range sd.Endpoints {
		if ed.Method.Name == name {
			return ed
		}
	}
	return nil
}

// HasUnaryEndpoint returns true if the service has at least one unary endpoint.
func (sd *ServiceData) HasUnaryEndpoint() bool {
	for _, ed := range sd.Endpoints {
		if ed.ServerStream == nil {
			return true
		}
	}
	return false
}

// HasStreamingEndpoint returns true if the service has at least one streaming
// endpoint.
func (sd *ServiceData) HasStreamingEndpoint() bool {
	for _, ed := range sd.Endpoints {
		if ed.ServerStream != nil {
			return true
		}
	}
	return false
}

// serviceHasViewedResult reports whether any generated transport section
// references the service views package through a viewed method result.
func serviceHasViewedResult(service *ServiceData) bool {
	for _, endpoint := range service.Endpoints {
		if endpoint.Method.ViewedResult != nil {
			return true
		}
	}
	return false
}

// serviceHasUnaryViewedResult reports whether client/encode_decode.go emits a
// response decoder that constructs and validates a viewed unary result.
func serviceHasUnaryViewedResult(service *ServiceData) bool {
	for _, endpoint := range service.Endpoints {
		if endpoint.ClientStream == nil && endpoint.Method.ViewedResult != nil {
			return true
		}
	}
	return false
}

// serviceHasViewedClientStream reports whether client.go emits a receive
// method that constructs and validates a viewed streaming result.
func serviceHasViewedClientStream(service *ServiceData) bool {
	for _, endpoint := range service.Endpoints {
		if endpoint.ClientStream != nil &&
			endpoint.ClientStream.RecvConvert != nil &&
			endpoint.Method.ViewedResult != nil {
			return true
		}
	}
	return false
}

// analyze creates the data necessary to render the code of the given service.
func (d *ServicesData) analyze(gs *expr.GRPCServiceExpr) *ServiceData {
	svc := d.ServicesData.Get(gs.Name())
	transportService := *svc
	transportService.PkgName = d.ServiceImport(svc.Name).Name
	svc = &transportService
	scope := codegen.NewNameScope()
	protobufPath := path.Join(d.GenPkg(), "grpc", svc.PathName, pbPkgName)
	pkg := d.PackageImport(protobufPath).Name
	svcVarN := scope.HashedUnique(gs.ServiceExpr, codegen.Goify(svc.Name, true))
	sd := &ServiceData{
		Service:             svc,
		ClientPkgName:       d.PackageImport(path.Join(d.GenPkg(), "grpc", svc.PathName, "client")).Name,
		ServerPkgName:       d.PackageImport(path.Join(d.GenPkg(), "grpc", svc.PathName, "server")).Name,
		Name:                svcVarN,
		Description:         svc.Description,
		PkgName:             pkg,
		ServerStruct:        "Server",
		ClientStruct:        "Client",
		ServerInit:          "New",
		ClientInit:          "NewClient",
		ServerInterface:     svcVarN + "Server",
		ClientInterface:     svcVarN + "Client",
		ClientInterfaceInit: fmt.Sprintf("%s.New%sClient", pkg, svcVarN),
		Scope:               scope,
	}
	sd.protobuf = newProtobufPackageCatalog(pkg)
	sd.protobuf.reserveName(sd.Name)
	protobufMessages := prepareProtobufPackage(gs, sd)
	for index, e := range gs.GRPCEndpoints {
		hasRequestMessage := !isEmpty(e.Request.Type)
		messages := protobufMessages[index]
		requestMessage := messages.request
		streamingRequest := messages.streamingRequest
		requestEnvelope := messages.requestEnvelope
		responseMessage := messages.response
		errorMessages := messages.errors
		collect := func(attribute *expr.AttributeExpr) *service.UserTypeData {
			record := sd.protobuf.message(attribute)
			if record == nil || record.data == nil {
				panic(fmt.Sprintf("no protobuf message collected for attribute of type %q", attribute.Type.Name())) // bug
			}
			return record.data
		}

		var (
			payloadRef      string
			resultRef       string
			viewedResultRef string
		)
		md := svc.Method(e.Name())
		if e.MethodExpr.Payload.Type != expr.Empty {
			svcctx := d.serviceTypeContext(sd, "server").Enter(e.MethodExpr.Payload)
			payloadRef = svcctx.Scope.Ref(e.MethodExpr.Payload, svcctx.Pkg(e.MethodExpr.Payload))
		}
		if e.MethodExpr.Result.Type != expr.Empty {
			svcctx := d.serviceTypeContext(sd, "server").Enter(e.MethodExpr.Result)
			resultRef = svcctx.Scope.Ref(e.MethodExpr.Result, svcctx.Pkg(e.MethodExpr.Result))
		}
		if md.ViewedResult != nil {
			viewedResultRef = md.ViewedResult.FullRef
		}
		errors := d.buildErrorsData(e, errorMessages, sd)
		// build request data
		payloadIdentity := expr.MethodPayloadExampleIdentity(e.MethodExpr)
		resultIdentity := expr.MethodResultExampleIdentity(e.MethodExpr)
		reqMD := d.extractMetadata(e.Metadata, e.MethodExpr.Payload, sd, "server", payloadIdentity)
		request := &RequestData{
			Description:   requestMessage.Description,
			Metadata:      reqMD,
			ServerConvert: d.buildRequestConvertData(requestMessage, e.MethodExpr.Payload, reqMD, e, sd, true),
			ClientConvert: d.buildRequestConvertData(requestMessage, e.MethodExpr.Payload, reqMD, e, sd, false),
		}
		if hasRequestMessage {
			request.PayloadMessage = collect(requestMessage)
		}
		if obj := expr.AsObject(requestMessage.Type); (obj != nil && len(*obj) > 0) || expr.IsUnion(requestMessage.Type) {
			// add the request message as the first argument to the CLI
			request.CLIArgs = append(request.CLIArgs, &InitArgData{
				Name:     "message",
				Ref:      "message",
				TypeName: protoBufGoFullTypeName(requestMessage, sd.PkgName, sd),
				TypeRef:  protoBufGoFullTypeRef(requestMessage, sd.PkgName, sd),
				Example:  d.Example(requestMessage, payloadIdentity),
			})
		}
		// pass the metadata as arguments to client CLI args
		request.CLIArgs = append(request.CLIArgs, initArgsFromMetadata(reqMD, "")...)
		switch {
		case requestEnvelope != nil:
			request.Message = collect(requestEnvelope)
			request.StreamEnvelope = buildStreamEnvelopeData(requestEnvelope, request.Message, sd)
			if e.LegacyStreamCompat() {
				request.LegacyDecode = d.buildLegacyDecodeData(e, sd)
			}
		case streamingRequest.Type != expr.Empty:
			request.Message = collect(streamingRequest)
		default:
			request.Message = collect(requestMessage)
		}

		// build response data
		serverResult, serverCtx := d.resultContext(e, sd, "server")
		clientResult, clientCtx := d.resultContext(e, sd, "client")
		hdrs := d.extractMetadata(e.Response.Headers, clientResult, sd, "client", resultIdentity)
		trlrs := d.extractMetadata(e.Response.Trailers, clientResult, sd, "client", resultIdentity)
		response := &ResponseData{
			StatusCode:    statusCodeToGRPCConst(e.Response.StatusCode),
			Description:   e.Response.Description,
			Headers:       hdrs,
			Trailers:      trlrs,
			ServerConvert: d.buildResponseConvertData(responseMessage, serverResult, serverCtx, hdrs, trlrs, e, sd, true),
			ClientConvert: d.buildResponseConvertData(responseMessage, clientResult, clientCtx, hdrs, trlrs, e, sd, false),
		}
		// If the endpoint is a streaming endpoint, no message is returned
		// by gRPC. Hence, no need to set response message.
		if responseMessage.Type != expr.Empty || !e.MethodExpr.IsStreaming() {
			response.Message = collect(responseMessage)
		}

		// gather security requirements
		var (
			msgSch service.SchemesData
			metSch service.SchemesData
		)
		for _, req := range e.Requirements {
			for _, sch := range req.Schemes {
				s := md.Requirements.Scheme(sch.SchemeName).Dup()
				s.In = sch.In
				switch s.In {
				case "message":
					msgSch = msgSch.Append(s)
				default:
					metSch = metSch.Append(s)
				}
			}
		}
		ed := &EndpointData{
			ServiceName:      svc.Name,
			PkgName:          sd.PkgName,
			ServicePkgName:   svc.PkgName,
			Method:           md,
			PayloadType:      e.MethodExpr.Payload.Type,
			PayloadRef:       payloadRef,
			ResultRef:        resultRef,
			ViewedResultRef:  viewedResultRef,
			Request:          request,
			Response:         response,
			MessageSchemes:   msgSch,
			MetadataSchemes:  metSch,
			Errors:           errors,
			ServerStruct:     sd.ServerStruct,
			ServerInterface:  sd.ServerInterface,
			ClientMethodName: protoBufify(md.VarName, true, true),
			ClientStruct:     sd.ClientStruct,
			ClientInterface:  sd.ClientInterface,
		}
		sd.Endpoints = append(sd.Endpoints, ed)
		if e.MethodExpr.IsStreaming() {
			ed.ServerStream = d.buildStreamData(e, streamingRequest, responseMessage, sd, true)
			ed.ClientStream = d.buildStreamData(e, streamingRequest, responseMessage, sd, false)
		}
	}
	return sd
}

// prepareProtobufPackage shapes every endpoint message, collects the complete
// package declaration set, and freezes messages and validators before any
// conversion or template data resolves their names.
func prepareProtobufPackage(serviceExpr *expr.GRPCServiceExpr, sd *ServiceData) []*protobufEndpointMessages {
	prepared := make([]*protobufEndpointMessages, len(serviceExpr.GRPCEndpoints))
	for index, endpoint := range serviceExpr.GRPCEndpoints {
		useStreamEnvelope := usesStreamEnvelope(endpoint)
		request := makeProtoBufMessage(
			endpoint.Request,
			protoBufify(endpoint.Name()+"_request", true, true),
			expr.GRPCRequestMessageExampleIdentity(endpoint.MethodExpr),
		)
		streamingRequest := endpoint.StreamingRequest
		if endpoint.MethodExpr.StreamingPayload.Type != expr.Empty {
			name := protoBufify(endpoint.Name()+"_streaming_request", true, true)
			if useStreamEnvelope {
				name = protoBufify(endpoint.Name()+"_stream_item", true, true)
			}
			streamingRequest = makeProtoBufMessage(
				endpoint.StreamingRequest,
				name,
				expr.GRPCStreamingRequestMessageExampleIdentity(endpoint.MethodExpr),
			)
		}
		var requestEnvelope *expr.AttributeExpr
		if useStreamEnvelope {
			requestEnvelope = makeProtoBufStreamEnvelope(
				request,
				streamingRequest,
				protoBufify(endpoint.Name()+"_streaming_request", true, true),
				expr.GRPCStreamingRequestMessageExampleIdentity(endpoint.MethodExpr),
			)
		}
		responseOwner := expr.GRPCResponseMessageExampleIdentity(endpoint.MethodExpr)
		if endpoint.MethodExpr.IsResultStreaming() {
			responseOwner = expr.GRPCStreamingResponseMessageExampleIdentity(endpoint.MethodExpr)
		}
		response := makeProtoBufMessage(
			endpoint.Response.Message,
			protoBufify(endpoint.Name()+"_response", true, true),
			responseOwner,
		)
		errors := make(map[string]*expr.AttributeExpr, len(endpoint.GRPCErrors))
		for _, grpcError := range endpoint.GRPCErrors {
			if grpcError.Type == expr.ErrorResult || !expr.IsObject(grpcError.Type) {
				continue
			}
			errors[grpcError.Name] = makeProtoBufMessage(
				grpcError.Response.Message,
				protoBufify(endpoint.Name()+"_"+grpcError.Name+"_error", true, true),
				expr.GRPCErrorMessageExampleIdentity(endpoint.MethodExpr, grpcError.ErrorExpr),
			)
		}
		prepared[index] = &protobufEndpointMessages{
			request:          request,
			streamingRequest: streamingRequest,
			requestEnvelope:  requestEnvelope,
			response:         response,
			errors:           errors,
		}
	}

	imported := make(map[string]struct{})
	collect := func(attribute *expr.AttributeExpr, source protobufMessageSource) {
		for _, protobufImport := range sd.protobuf.collectMessage(attribute, source, sd) {
			if _, ok := imported[protobufImport]; ok {
				continue
			}
			imported[protobufImport] = struct{}{}
			sd.ProtoImports = append(sd.ProtoImports, protobufImport)
		}
	}
	for index, endpoint := range serviceExpr.GRPCEndpoints {
		messages := prepared[index]
		requestSource := protobufRootMessageSource(endpoint.Request, endpoint, nil, protobufRequestMessage)
		streamingSource := protobufRootMessageSource(endpoint.StreamingRequest, endpoint, nil, protobufStreamingRequestMessage)
		responseSource := protobufRootMessageSource(endpoint.Response.Message, endpoint, nil, protobufResponseMessage)
		sd.protobuf.bindRootSource(messages.request, requestSource)
		if messages.streamingRequest.Type != expr.Empty {
			sd.protobuf.bindRootSource(messages.streamingRequest, streamingSource)
		}
		sd.protobuf.bindRootSource(messages.response, responseSource)
		for _, grpcError := range endpoint.GRPCErrors {
			message := messages.errors[grpcError.Name]
			if message == nil {
				continue
			}
			errorSource := protobufRootMessageSource(
				grpcError.Response.Message,
				endpoint,
				grpcError,
				protobufErrorMessage,
			)
			sd.protobuf.bindRootSource(message, errorSource)
			collect(message, errorSource)
		}
		requestNeeded := !isEmpty(endpoint.Request.Type) ||
			(messages.requestEnvelope == nil && messages.streamingRequest.Type == expr.Empty)
		if requestNeeded {
			collect(messages.request, requestSource)
		}
		if messages.requestEnvelope != nil {
			envelopeSource := protobufMessageSource{synthetic: protobufSyntheticMessage{
				endpoint: endpoint,
				role:     protobufStreamEnvelopeMessage,
			}}
			sd.protobuf.bindRootSource(messages.requestEnvelope, envelopeSource)
			collect(messages.requestEnvelope, envelopeSource)
		}
		if messages.streamingRequest.Type != expr.Empty {
			collect(messages.streamingRequest, streamingSource)
		}
		if messages.response.Type != expr.Empty || !endpoint.MethodExpr.IsStreaming() {
			collect(messages.response, responseSource)
		}
	}
	sd.Messages = sd.protobuf.freezeMessages(sd)

	for index, endpoint := range serviceExpr.GRPCEndpoints {
		messages := prepared[index]
		if sd.protobuf.message(messages.request) != nil {
			sd.protobuf.collectValidation(messages.request, validateServer, "message", "message")
		}
		if sd.protobuf.message(messages.response) != nil {
			sd.protobuf.collectValidation(messages.response, validateClient, "message", "message")
		}
		for _, grpcError := range endpoint.GRPCErrors {
			if message := messages.errors[grpcError.Name]; message != nil {
				sd.protobuf.collectValidation(message, validateClient, "errmsg", "errmsg")
			}
		}
		if endpoint.MethodExpr.StreamingPayload.Type != expr.Empty {
			sd.protobuf.collectValidation(messages.streamingRequest, validateServer, "stream", "stream")
		}
	}
	sd.validations = sd.protobuf.freezeValidations(sd)
	return prepared
}

// protobufRootMessageSource identifies a root message by the authored service
// declaration whose value it carries. Endpoint roles identify only messages
// whose service value is inline or compiler-created. The shaped wire attribute
// is a fallback because explicit Message DSL may itself name a declaration.
func protobufRootMessageSource(attribute *expr.AttributeExpr, endpoint *expr.GRPCEndpointExpr, grpcError *expr.GRPCErrorExpr, role protobufSyntheticRole) protobufMessageSource {
	var serviceAttribute *expr.AttributeExpr
	switch role {
	case protobufRequestMessage:
		serviceAttribute = endpoint.MethodExpr.Payload
	case protobufStreamingRequestMessage:
		serviceAttribute = endpoint.MethodExpr.StreamingPayload
	case protobufResponseMessage:
		serviceAttribute = endpoint.MethodExpr.Result
	case protobufErrorMessage:
		if methodError := endpoint.MethodExpr.Error(grpcError.Name); methodError != nil {
			serviceAttribute = methodError.AttributeExpr
		}
	}
	if serviceAttribute != nil {
		if userType, ok := serviceAttribute.Type.(expr.UserType); ok {
			return protobufMessageSource{origin: userType.Origin()}
		}
	}
	if userType, ok := attribute.Type.(expr.UserType); ok {
		return protobufMessageSource{origin: userType.Origin()}
	}
	return protobufMessageSource{synthetic: protobufSyntheticMessage{
		endpoint: endpoint,
		error:    grpcError,
		role:     role,
	}}
}

// addValidation returns the frozen validation helper for the given protobuf
// message on the generated server or client side.
//
// req if true indicates that the validation is generated for validating
// request (server-side) messages.
func addValidation(att *expr.AttributeExpr, sd *ServiceData, req bool) *ValidationData {
	kind := validateClient
	if req {
		kind = validateServer
	}
	return sd.protobuf.validation(att, kind)
}

// userTypeAttribute returns the attribute of the given user type.
func userTypeAttribute(ut expr.UserType) *expr.AttributeExpr {
	att := ut.Attribute()
	if rt, ok := ut.(*expr.ResultTypeExpr); ok {
		// Result type collections are wrapper user types themselves: the
		// wrappedAttrMeta marker lives directly on their attribute when the
		// collection was wrapped as a whole message (makeProtoBufMessage) and
		// on a nested wrapper user type when the collection was wrapped in
		// place as a field type (makeProtoBufMessageR).
		if len(att.Meta[wrappedAttrMeta]) > 0 || isWrappedAttr(att) {
			if expr.IsArray(unwrapAttr(att).Type) {
				// result type collection
				att = &expr.AttributeExpr{Type: expr.AsObject(rt)}
			}
		}
	}
	return att
}

// buildRequestConvertData builds the convert data for the server and client
// requests.
//   - server side - converts the one-shot gRPC request message (if any) and
//     gRPC metadata to the method payload type.
//   - client side - converts the method payload type to the one-shot gRPC
//     request message sent before any stream items.
//
// svr param indicates that the convert data is generated for server side.
func (d *ServicesData) buildRequestConvertData(request, payload *expr.AttributeExpr, md []*MetadataData, e *expr.GRPCEndpointExpr, sd *ServiceData, svr bool) *ConvertData {
	if svr && isEmpty(payload.Type) {
		return nil
	}
	if !svr && e.MethodExpr.IsPayloadStreaming() && isEmpty(request.Type) {
		return nil
	}
	if svr && e.MethodExpr.IsPayloadStreaming() && isEmpty(request.Type) && !expr.IsObject(payload.Type) {
		return nil
	}

	svc := sd.Service
	method := svc.Method(e.Name())
	side := "client"
	if svr {
		side = "server"
	}
	svcCtx := d.serviceTypeContext(sd, side).Enter(payload)
	if svr {
		// server side
		data := d.buildInitData(request, payload, "message", "v", svcCtx, method.Payload, false, false, sd, expr.MethodPayloadExampleIdentity(e.MethodExpr))
		data.Name = fmt.Sprintf("New%sPayload", codegen.Goify(e.Name(), true))
		data.Description = fmt.Sprintf("%s builds the payload of the %q endpoint of the %q service from the gRPC request type.", data.Name, e.Name(), svc.Name)
		// pass the metadata as arguments to payload constructor in server
		data.Args = append(data.Args, initArgsFromMetadata(md, data.ReturnVarName)...)
		return &ConvertData{
			SrcName:    protoBufGoFullTypeName(request, sd.PkgName, sd),
			SrcRef:     protoBufGoFullTypeRef(request, sd.PkgName, sd),
			TgtName:    svcCtx.Scope.Name(payload, svcCtx.Pkg(payload), svcCtx.Pointer, svcCtx.UseDefault),
			TgtRef:     svcCtx.Scope.Ref(payload, svcCtx.Pkg(payload)),
			Init:       data,
			Validation: addValidation(request, sd, true),
		}
	}

	// client side
	data := d.buildInitData(payload, request, "payload", "message", svcCtx, method.Payload, true, false, sd, expr.MethodPayloadExampleIdentity(e.MethodExpr))
	data.Description = fmt.Sprintf("%s builds the gRPC request type from the payload of the %q endpoint of the %q service.", data.Name, e.Name(), svc.Name)
	return &ConvertData{
		SrcName: svcCtx.Scope.Name(payload, svcCtx.Pkg(payload), svcCtx.Pointer, svcCtx.UseDefault),
		SrcRef:  svcCtx.Scope.Ref(payload, svcCtx.Pkg(payload)),
		TgtName: protoBufGoFullTypeName(request, sd.PkgName, sd),
		TgtRef:  protoBufGoFullTypeRef(request, sd.PkgName, sd),
		Init:    data,
	}
}

// buildLegacyDecodeData computes the data needed to decode requests sent by
// legacy stream protocol clients which carry the one-shot method payload in
// gRPC request metadata. The metadata layout mirrors what pre-envelope
// versions of goa generated: every payload attribute not explicitly mapped
// to metadata is carried under its own name and non-object payloads travel
// under the reserved "goa_payload" key.
func (d *ServicesData) buildLegacyDecodeData(e *expr.GRPCEndpointExpr, sd *ServiceData) *LegacyDecodeData {
	svc := sd.Service
	payload := e.MethodExpr.Payload
	legacyMD := expr.DupMappedAtt(e.Metadata)
	mdObj := expr.AsObject(legacyMD.Type)
	if pobj := expr.AsObject(payload.Type); pobj != nil {
		for _, nat := range *pobj {
			if mdObj.Attribute(nat.Name) == nil {
				mdObj.Set(nat.Name, expr.DupAtt(nat.Attribute))
			}
			if payload.IsRequired(nat.Name) {
				legacyMD.Validation.AddRequired(nat.Name)
			}
		}
	} else {
		mdObj.Set("goa_payload", expr.DupAtt(payload))
		legacyMD.Validation.AddRequired("goa_payload")
	}
	owner := expr.MethodPayloadExampleIdentity(e.MethodExpr)
	md := d.extractMetadata(legacyMD, payload, sd, "server", owner)
	data := &LegacyDecodeData{
		FuncName: fmt.Sprintf("decode%sLegacyRequest", codegen.Goify(e.Name(), true)),
		Metadata: md,
	}
	if expr.IsObject(payload.Type) {
		svcCtx := d.serviceTypeContext(sd, "server").Enter(payload)
		init := d.buildInitData(&expr.AttributeExpr{Type: expr.Empty}, payload, "message", "v", svcCtx, sd.Service.Method(e.Name()).Payload, false, false, sd, owner)
		init.Name = fmt.Sprintf("New%sPayloadFromMetadata", codegen.Goify(e.Name(), true))
		init.Description = fmt.Sprintf("%s builds the payload of the %q endpoint of the %q service from the gRPC request metadata sent by legacy stream protocol clients.", init.Name, e.Name(), svc.Name)
		init.Args = append(init.Args, initArgsFromMetadata(md, init.ReturnVarName)...)
		data.ServerConvert = &ConvertData{
			TgtName: svcCtx.Scope.Name(payload, svcCtx.Pkg(payload), svcCtx.Pointer, svcCtx.UseDefault),
			TgtRef:  svcCtx.Scope.Ref(payload, svcCtx.Pkg(payload)),
			Init:    init,
		}
	}
	return data
}

// buildResponseConvertData builds the convert data for the server and client
// responses.
//   - server side - converts method result type to generated gRPC response
//     type in *.pb.go
//   - client side - converts generated gRPC response type in *.pb.go and
//     response metadata to method result type.
//
// svr param indicates that the convert data is generated for server side.
func (d *ServicesData) buildResponseConvertData(response, result *expr.AttributeExpr, svcCtx *codegen.AttributeContext, hdrs, trlrs []*MetadataData, e *expr.GRPCEndpointExpr, sd *ServiceData, svr bool) *ConvertData {
	if !svr && (e.MethodExpr.IsStreaming() || isEmpty(e.MethodExpr.Result.Type)) {
		return nil
	}
	svc := sd.Service
	method := svc.Method(e.Name())
	resultName := method.Result
	if _, ok := result.Type.(expr.UserType); ok {
		resultName = codegen.Goify(result.Type.Name(), true)
	}
	if svr {
		// server side
		data := d.buildInitData(result, response, "result", "message", svcCtx, resultName, true, false, sd, expr.MethodResultExampleIdentity(e.MethodExpr))
		data.Description = fmt.Sprintf("%s builds the gRPC response type from the result of the %q endpoint of the %q service.", data.Name, e.Name(), svc.Name)
		return &ConvertData{
			SrcName: svcCtx.Scope.Name(result, svcCtx.Pkg(result), svcCtx.Pointer, svcCtx.UseDefault),
			SrcRef:  svcCtx.Scope.Ref(result, svcCtx.Pkg(result)),
			TgtName: protoBufGoFullTypeName(response, sd.PkgName, sd),
			TgtRef:  protoBufGoFullTypeRef(response, sd.PkgName, sd),
			Init:    data,
		}
	}

	// client side
	data := d.buildInitData(response, result, "message", "result", svcCtx, resultName, false, false, sd, expr.MethodResultExampleIdentity(e.MethodExpr))
	data.Name = fmt.Sprintf("New%sResult", codegen.Goify(e.Name(), true))
	data.Description = fmt.Sprintf("%s builds the result type of the %q endpoint of the %q service from the gRPC response type.", data.Name, e.Name(), svc.Name)
	// pass the headers as arguments to result constructor in client
	data.Args = append(data.Args, initArgsFromMetadata(hdrs, data.ReturnVarName)...)
	// pass the trailers as arguments to result constructor in client
	data.Args = append(data.Args, initArgsFromMetadata(trlrs, data.ReturnVarName)...)
	return &ConvertData{
		SrcName:    protoBufGoFullTypeName(response, sd.PkgName, sd),
		SrcRef:     protoBufGoFullTypeRef(response, sd.PkgName, sd),
		TgtName:    svcCtx.Scope.Name(result, svcCtx.Pkg(result), svcCtx.Pointer, svcCtx.UseDefault),
		TgtRef:     svcCtx.Scope.Ref(result, svcCtx.Pkg(result)),
		Init:       data,
		Validation: addValidation(response, sd, false),
	}
}

// buildInitData builds the transformation code to convert source to target.
//
// source, target are the source and target attributes used in the
// transformation
// sourceVar, targetVar are the source and target variable names used in the
// transformation
// svcCtx is the attribute context for service type
// proto if true indicates the target type is a protocol buffer type
func (d *ServicesData) buildInitData(source, target *expr.AttributeExpr, sourceVar, targetVar string, svcCtx *codegen.AttributeContext, serviceTypeName string, proto, usesrc bool, sd *ServiceData, owner expr.ExampleIdentity) *InitData {
	pbCtx := protoBufTypeContext(sd.PkgName, sd, false)
	name := "New"
	srcCtx := pbCtx
	tgtCtx := svcCtx
	if proto {
		srcCtx = svcCtx
		tgtCtx = pbCtx
		name += "Proto"
	}
	var sourceTypeName, targetTypeName func() string
	if proto {
		sourceTypeName = func() string { return serviceTypeName }
		targetTypeName = func() string { return protoBufGoTypeName(target, sd) }
	} else {
		sourceTypeName = func() string { return protoBufGoTypeName(source, sd) }
		targetTypeName = func() string { return serviceTypeName }
	}
	isStruct := expr.IsObject(target.Type) || expr.IsUnion(target.Type)
	if _, ok := source.Type.(expr.UserType); ok && usesrc {
		name += sourceTypeName()
	}
	n := serviceTypeName
	if isStruct {
		n = targetTypeName()
	} else {
		// If target is array, map, or primitive the name will be suffixed with
		// the definition (e.g int, []string, map[int]string) which is incorrect.
		n = sourceTypeName()
	}
	name += n
	code, helpers, err := protoBufTransform(source, target, sourceVar, targetVar, srcCtx, tgtCtx, proto, true)
	if err != nil {
		panic(err) // bug
	}
	sd.transformHelpers = codegen.AppendHelpers(sd.transformHelpers, helpers)
	var args []*InitArgData
	if (!proto && !isEmpty(source.Type)) || (proto && !isEmpty(target.Type)) {
		args = []*InitArgData{{
			Name:     sourceVar,
			Ref:      sourceVar,
			TypeName: srcCtx.Scope.Name(source, srcCtx.Pkg(source), srcCtx.Pointer, srcCtx.UseDefault),
			TypeRef:  srcCtx.Scope.Ref(source, srcCtx.Pkg(source)),
			Example:  d.Example(source, owner),
		}}
	}
	return &InitData{
		Name:           name,
		ReturnVarName:  targetVar,
		ReturnTypeRef:  tgtCtx.Scope.Ref(target, tgtCtx.Pkg(target)),
		ReturnIsStruct: isStruct,
		ReturnTypePkg:  tgtCtx.Pkg(target),
		Code:           code,
		Args:           args,
	}
}

// buildErrorsData builds the error data for all the error responses in the
// endpoint expression. The response message for each error response are
// inferred from the method's error expression if not specified explicitly.
// errorMessages maps error names to the protobuf shaped copy of their
// response message derived by analyze; errors without a custom object type
// have no entry.
func (d *ServicesData) buildErrorsData(e *expr.GRPCEndpointExpr, errorMessages map[string]*expr.AttributeExpr, sd *ServiceData) []*ErrorData {
	errors := make([]*ErrorData, 0, len(e.GRPCErrors))
	for _, v := range e.GRPCErrors {
		responseData := &ResponseData{
			StatusCode:    statusCodeToGRPCConst(v.Response.StatusCode),
			Description:   v.Response.Description,
			ServerConvert: d.buildErrorConvertData(v, e, errorMessages[v.Name], sd, true),
			ClientConvert: d.buildErrorConvertData(v, e, errorMessages[v.Name], sd, false),
		}
		svcctx := d.serviceTypeContext(sd, "server").Enter(v.AttributeExpr)
		errors = append(errors, &ErrorData{
			Name:     v.Name,
			Ref:      svcctx.Scope.Ref(v.AttributeExpr, svcctx.Pkg(v.AttributeExpr)),
			Response: responseData,
		})
	}
	return errors
}

// buildErrorConvertData builds the convert data for the given error response.
// message is the protobuf shaped copy of the error response message derived
// by analyze; it is nil for default errors and non-object error types.
func (d *ServicesData) buildErrorConvertData(ge *expr.GRPCErrorExpr, e *expr.GRPCEndpointExpr, message *expr.AttributeExpr, sd *ServiceData, svr bool) *ConvertData {
	// No need to build transformation functions for default error or non-object
	// types.
	if ge.Type == expr.ErrorResult || !expr.IsObject(ge.Type) {
		return nil
	}
	svc := sd.Service
	side := "client"
	if svr {
		side = "server"
	}
	svcCtx := d.serviceTypeContext(sd, side).Enter(ge.AttributeExpr)
	errorTypeName := ""
	for _, serviceError := range sd.Service.Method(e.Name()).Errors {
		if serviceError.ErrName == ge.Name {
			errorTypeName = serviceError.TypeName
			break
		}
	}
	if svr {
		// server side
		owner := expr.MethodErrorExampleIdentity(e.MethodExpr, ge.ErrorExpr)
		data := d.buildInitData(ge.AttributeExpr, message, "er", "message", svcCtx, errorTypeName, true, false, sd, owner)
		data.Name = fmt.Sprintf("New%s%sError", codegen.Goify(e.Name(), true), codegen.Goify(ge.Name, true))
		data.Description = fmt.Sprintf("%s builds the gRPC error response type from the error of the %q endpoint of the %q service.", data.Name, e.Name(), svc.Name)
		return &ConvertData{
			SrcName: svcCtx.Scope.Name(ge.AttributeExpr, svcCtx.Pkg(ge.AttributeExpr), svcCtx.Pointer, svcCtx.UseDefault),
			SrcRef:  svcCtx.Scope.Ref(ge.AttributeExpr, svcCtx.Pkg(ge.AttributeExpr)),
			TgtName: protoBufGoFullTypeName(message, sd.PkgName, sd),
			TgtRef:  protoBufGoFullTypeRef(message, sd.PkgName, sd),
			Init:    data,
		}
	}

	// client side
	owner := expr.MethodErrorExampleIdentity(e.MethodExpr, ge.ErrorExpr)
	data := d.buildInitData(message, ge.AttributeExpr, "message", "er", svcCtx, errorTypeName, false, false, sd, owner)
	data.Name = fmt.Sprintf("New%s%sError", codegen.Goify(e.Name(), true), codegen.Goify(ge.Name, true))
	data.Description = fmt.Sprintf("%s builds the error type of the %q endpoint of the %q service from the gRPC error response type.", data.Name, e.Name(), svc.Name)
	return &ConvertData{
		SrcName:    protoBufGoFullTypeName(message, sd.PkgName, sd),
		SrcRef:     protoBufGoFullTypeRef(message, sd.PkgName, sd),
		TgtName:    svcCtx.Scope.Name(ge.AttributeExpr, svcCtx.Pkg(ge.AttributeExpr), svcCtx.Pointer, svcCtx.UseDefault),
		TgtRef:     svcCtx.Scope.Ref(ge.AttributeExpr, svcCtx.Pkg(ge.AttributeExpr)),
		Init:       data,
		Validation: addValidation(message, sd, false),
	}
}

// buildStreamData builds the StreamData for the server and client streams.
//
// streamingRequest and responseMessage are the protobuf shaped copies of the
// endpoint streaming request and response message derived by analyze.
//
// svr param indicates that the stream data is built for the server.
func (d *ServicesData) buildStreamData(e *expr.GRPCEndpointExpr, streamingRequest, responseMessage *expr.AttributeExpr, sd *ServiceData, svr bool) *StreamData {
	var (
		varn                string
		intName             string
		svcInt              string
		sendName            string
		sendDesc            string
		sendWithContextName string
		sendWithContextDesc string
		sendRef             string
		sendConvert         *ConvertData
		recvName            string
		recvDesc            string
		recvWithContextName string
		recvWithContextDesc string
		recvRef             string
		recvConvert         *ConvertData
		mustClose           bool
		typ                 string
	)
	svc := sd.Service
	ed := sd.Endpoint(e.Name())
	md := ed.Method
	streamingPayloadName := md.StreamingPayload
	resultName := md.StreamingResult
	if resultName == "" {
		resultName = md.Result
	}
	side := "client"
	if svr {
		side = "server"
	}
	svcCtx := d.serviceTypeContext(sd, side).Enter(e.MethodExpr.StreamingPayload)
	result, resCtx := d.resultContext(e, sd, side)
	if _, ok := result.Type.(expr.UserType); ok {
		resultName = codegen.Goify(result.Type.Name(), true)
	}
	resVar := "result"
	if md.ViewedResult != nil {
		resVar = "vresult"
	}
	if svr {
		typ = "server"
		varn = md.ServerStream.VarName
		intName = fmt.Sprintf("%s.%s_%sServer", sd.PkgName, svc.StructName, md.VarName)
		svcInt = fmt.Sprintf("%s.%s", svc.PkgName, md.ServerStream.Interface)
		if e.MethodExpr.Result.Type != expr.Empty {
			sendName = md.ServerStream.SendName
			sendRef = ed.ResultRef
			sendWithContextName = md.ServerStream.SendWithContextName
			sendConvert = &ConvertData{
				SrcName: resCtx.Scope.Name(result, resCtx.Pkg(result), resCtx.Pointer, resCtx.UseDefault),
				SrcRef:  resCtx.Scope.Ref(result, resCtx.Pkg(result)),
				TgtName: protoBufGoFullTypeName(responseMessage, sd.PkgName, sd),
				TgtRef:  protoBufGoFullTypeRef(responseMessage, sd.PkgName, sd),
				Init:    d.buildInitData(result, responseMessage, resVar, "v", resCtx, resultName, true, true, sd, expr.MethodStreamingResultExampleIdentity(e.MethodExpr)),
			}
		}
		if e.MethodExpr.StreamingPayload.Type != expr.Empty {
			recvName = md.ServerStream.RecvName
			recvWithContextName = md.ServerStream.RecvWithContextName
			recvRef = svcCtx.Scope.Ref(e.MethodExpr.StreamingPayload, svcCtx.Pkg(e.MethodExpr.StreamingPayload))
			recvConvert = &ConvertData{
				SrcName:    protoBufGoFullTypeName(streamingRequest, sd.PkgName, sd),
				SrcRef:     protoBufGoFullTypeRef(streamingRequest, sd.PkgName, sd),
				TgtName:    svcCtx.Scope.Name(e.MethodExpr.StreamingPayload, svcCtx.Pkg(e.MethodExpr.StreamingPayload), svcCtx.Pointer, svcCtx.UseDefault),
				TgtRef:     recvRef,
				Init:       d.buildInitData(streamingRequest, e.MethodExpr.StreamingPayload, "v", "spayload", svcCtx, streamingPayloadName, false, true, sd, expr.MethodStreamingPayloadExampleIdentity(e.MethodExpr)),
				Validation: addValidation(streamingRequest, sd, true),
			}
		}
		mustClose = md.ServerStream.MustClose
	} else {
		typ = "client"
		varn = md.ClientStream.VarName
		intName = fmt.Sprintf("%s.%s_%sClient", sd.PkgName, svc.StructName, md.VarName)
		svcInt = fmt.Sprintf("%s.%s", svc.PkgName, md.ClientStream.Interface)
		if e.MethodExpr.StreamingPayload.Type != expr.Empty {
			sendName = md.ClientStream.SendName
			sendWithContextName = md.ClientStream.SendWithContextName
			sendRef = svcCtx.Scope.Ref(e.MethodExpr.StreamingPayload, svcCtx.Pkg(e.MethodExpr.StreamingPayload))
			sendConvert = &ConvertData{
				SrcName: svcCtx.Scope.Name(e.MethodExpr.StreamingPayload, svcCtx.Pkg(e.MethodExpr.StreamingPayload), svcCtx.Pointer, svcCtx.UseDefault),
				SrcRef:  sendRef,
				TgtName: protoBufGoFullTypeName(streamingRequest, sd.PkgName, sd),
				TgtRef:  protoBufGoFullTypeRef(streamingRequest, sd.PkgName, sd),
				Init:    d.buildInitData(e.MethodExpr.StreamingPayload, streamingRequest, "spayload", "v", svcCtx, streamingPayloadName, true, true, sd, expr.MethodStreamingPayloadExampleIdentity(e.MethodExpr)),
			}
		}
		if e.MethodExpr.Result.Type != expr.Empty {
			recvName = md.ClientStream.RecvName
			recvWithContextName = md.ClientStream.RecvWithContextName
			recvRef = ed.ResultRef
			recvConvert = &ConvertData{
				SrcName:    protoBufGoFullTypeName(responseMessage, sd.PkgName, sd),
				SrcRef:     protoBufGoFullTypeRef(responseMessage, sd.PkgName, sd),
				TgtName:    resCtx.Scope.Name(result, resCtx.Pkg(result), resCtx.Pointer, resCtx.UseDefault),
				TgtRef:     resCtx.Scope.Ref(result, resCtx.Pkg(result)),
				Init:       d.buildInitData(responseMessage, result, "v", resVar, resCtx, resultName, false, true, sd, expr.MethodStreamingResultExampleIdentity(e.MethodExpr)),
				Validation: addValidation(responseMessage, sd, false),
			}
		}
		mustClose = md.ClientStream.MustClose
	}
	if sendConvert != nil {
		sendDesc = fmt.Sprintf("%s streams instances of %q to the %q endpoint gRPC stream.", sendName, sendConvert.TgtName, md.Name)
		sendWithContextDesc = fmt.Sprintf("%s streams instances of %q to the %q endpoint gRPC stream with context.", sendWithContextName, sendConvert.TgtName, md.Name)
	}
	if recvConvert != nil {
		recvDesc = fmt.Sprintf("%s reads instances of %q from the %q endpoint gRPC stream.", recvName, recvConvert.SrcName, md.Name)
		recvWithContextDesc = fmt.Sprintf("%s reads instances of %q from the %q endpoint gRPC stream with context.", recvWithContextName, recvConvert.SrcName, md.Name)
	}
	return &StreamData{
		VarName:             varn,
		Type:                typ,
		Interface:           intName,
		ServiceInterface:    svcInt,
		Endpoint:            ed,
		SendName:            sendName,
		SendDesc:            sendDesc,
		SendWithContextName: sendWithContextName,
		SendWithContextDesc: sendWithContextDesc,
		SendRef:             sendRef,
		SendConvert:         sendConvert,
		RecvName:            recvName,
		RecvDesc:            recvDesc,
		RecvWithContextName: recvWithContextName,
		RecvWithContextDesc: recvWithContextDesc,
		RecvRef:             recvRef,
		RecvConvert:         recvConvert,
		MustClose:           mustClose,
	}
}

// extractMetadata collects the request/response metadata from the given
// metadata attribute and service type (payload/result).
func (d *ServicesData) extractMetadata(a *expr.MappedAttributeExpr, service *expr.AttributeExpr, sd *ServiceData, side string, owner expr.ExampleIdentity) []*MetadataData {
	var metadata []*MetadataData
	codegen.WalkMappedAttr(a, func(name, elem string, required bool, c *expr.AttributeExpr) error { // nolint: errcheck
		wire := nativeMetadataAttribute(c)
		arr := expr.AsArray(wire.Type)
		wireCtx := codegen.NewAttributeContext(false, false, true, "", codegen.NewNameScope()).Enter(wire)
		serviceField := service
		ft := service.Type
		varn := codegen.Goify(name, false)
		fieldName := codegen.Goify(name, true)
		var pointer bool
		if !expr.IsObject(service.Type) {
			fieldName = ""
		} else {
			pointer = service.IsPrimitivePointer(name, true)
			serviceField = service.Find(name)
			ft = serviceField.Type
		}
		typeRef := wireCtx.Scope.Ref(wire, wireCtx.Pkg(wire))
		if pointer {
			typeRef = "*" + typeRef
		}
		serviceVar := "payload"
		encodeSide := "client"
		if side == "client" {
			serviceVar = "result"
			encodeSide = "server"
		}
		fieldRef := serviceVar
		targetRef := metadataTargetPlaceholder
		if fieldName != "" {
			fieldRef += "." + fieldName
			targetRef += "." + fieldName
		}
		wireVar := varn + "Wire"
		encodeCode := d.metadataTransform(wire, serviceField, fieldRef, wireVar, sd, encodeSide, pointer, true)
		decodeCode := d.metadataTransform(wire, serviceField, varn, targetRef, sd, side, pointer, false)
		metadata = append(metadata, &MetadataData{
			Name:             elem,
			AttributeName:    name,
			Description:      wire.Description,
			FieldName:        fieldName,
			FieldType:        ft,
			ServiceAttribute: serviceField,
			WireAttribute:    wire,
			VarName:          varn,
			WireVarName:      wireVar,
			EncodeCode:       encodeCode,
			DecodeCode:       decodeCode,
			Required:         required,
			Type:             wire.Type,
			TypeName:         wireCtx.Scope.Name(wire, wireCtx.Pkg(wire), false, true),
			TypeRef:          typeRef,
			Pointer:          pointer,
			Slice:            arr != nil,
			StringSlice:      arr != nil && arr.ElemType.Type.Kind() == expr.StringKind,
			Validate:         codegen.AttributeValidationCode(wire, nil, wireCtx, required, false, varn, name),
			DefaultValue:     wire.DefaultValue,
			Example:          d.FieldExample(wire, service, name, owner),
		})
		return nil
	})
	return metadata
}

// metadataTransform generates the canonical conversion between a detached
// metadata value and its service field in the package that renders the code.
func (d *ServicesData) metadataTransform(wire, serviceField *expr.AttributeExpr, sourceVar, targetVar string, sd *ServiceData, side string, pointer, encode bool) string {
	wireCtx := codegen.NewAttributeContext(false, false, true, "", codegen.NewNameScope()).Enter(wire)
	serviceCtx := d.serviceTypeContext(sd, side).Enter(serviceField)
	source, target := wire, serviceField
	sourceCtx, targetCtx := wireCtx, serviceCtx
	if encode {
		source, target = serviceField, wire
		sourceCtx, targetCtx = serviceCtx, wireCtx
	}
	if pointer {
		sourceVar = "*" + sourceVar
	}
	if encode {
		code, helpers, err := codegen.GoTransform(source, target, sourceVar, targetVar, sourceCtx, targetCtx, "", true)
		if err != nil {
			panic(err)
		}
		sd.transformHelpers = codegen.AppendHelpers(sd.transformHelpers, helpers)
		return code
	}
	if !pointer {
		code, helpers, err := codegen.GoTransform(source, target, sourceVar, targetVar, sourceCtx, targetCtx, "", false)
		if err != nil {
			panic(err)
		}
		sd.transformHelpers = codegen.AppendHelpers(sd.transformHelpers, helpers)
		return code
	}
	converted := codegen.Goify(strings.TrimPrefix(sourceVar, "*"), false) + "Service"
	code, helpers, err := codegen.GoTransform(source, target, sourceVar, converted, sourceCtx, targetCtx, "", true)
	if err != nil {
		panic(err)
	}
	sd.transformHelpers = codegen.AppendHelpers(sd.transformHelpers, helpers)
	return "if " + strings.TrimPrefix(sourceVar, "*") + " != nil {\n" + code + "\n" + targetVar + " = &" + converted + "\n}\n"
}

// initArgsFromMetadata converts the given metadata into constructor arguments
// so the metadata values can be passed to the generated init functions.
func initArgsFromMetadata(md []*MetadataData, targetVar string) []*InitArgData {
	args := make([]*InitArgData, len(md))
	for i, m := range md {
		initCode := ""
		if targetVar != "" {
			initCode = strings.ReplaceAll(m.DecodeCode, metadataTargetPlaceholder, targetVar)
		}
		args[i] = &InitArgData{
			Name:         m.VarName,
			Ref:          m.VarName,
			FieldName:    m.FieldName,
			FieldType:    m.FieldType,
			InitCode:     initCode,
			TypeName:     m.TypeName,
			TypeRef:      m.TypeRef,
			Type:         m.Type,
			Pointer:      m.Pointer,
			Required:     m.Required,
			Validate:     m.Validate,
			Example:      m.Example,
			DefaultValue: m.DefaultValue,
		}
	}
	return args
}

// usesStreamEnvelope reports whether the transport needs a typed stream
// envelope to carry both the one-shot method payload and streaming payload
// items.
func usesStreamEnvelope(e *expr.GRPCEndpointExpr) bool {
	return e.MethodExpr.IsPayloadStreaming() && !isEmpty(e.Request.Type)
}

// makeProtoBufStreamEnvelope builds the protobuf stream envelope that carries
// the initial request payload frame and subsequent stream item frames.
func makeProtoBufStreamEnvelope(request, stream *expr.AttributeExpr, tname string, owner expr.ExampleIdentity) *expr.AttributeExpr {
	initial := expr.DupAtt(request)
	initial.Meta = initial.Meta.Dup()
	initial.Meta["rpc:tag"] = []string{"1"}
	streamItem := expr.DupAtt(stream)
	streamItem.Meta = streamItem.Meta.Dup()
	streamItem.Meta["rpc:tag"] = []string{"2"}
	envelope := &expr.AttributeExpr{
		Type: &expr.Object{
			&expr.NamedAttributeExpr{
				Name: "body",
				Attribute: &expr.AttributeExpr{
					Type: &expr.Union{
						TypeName: "body",
						Values: []*expr.NamedAttributeExpr{
							{Name: "initial_payload", Attribute: initial},
							{Name: "stream_item", Attribute: streamItem},
						},
					},
				},
			},
		},
		Validation: &expr.ValidationExpr{Required: []string{"body"}},
	}
	return makeProtoBufMessage(envelope, tname, owner)
}

// buildStreamEnvelopeData computes the generated Go names for the protobuf
// oneof field and wrapper types of the synthesized stream envelope.
func buildStreamEnvelopeData(envelope *expr.AttributeExpr, message *service.UserTypeData, sd *ServiceData) *StreamEnvelopeData {
	body := envelope.Find("body")
	union := expr.AsUnion(body.Type)
	scope := &protoBufScope{service: sd}
	fieldName := scope.Field(body, union.TypeName, true)
	initialFieldName := scope.Field(union.Values[0].Attribute, union.Values[0].Name, true)
	streamItemFieldName := scope.Field(union.Values[1].Attribute, union.Values[1].Name, true)
	return &StreamEnvelopeData{
		FieldName:            fieldName,
		InitialFieldName:     initialFieldName,
		InitialWrapperRef:    sd.PkgName + "." + protocOneofWrapperRef(message.VarName, initialFieldName),
		StreamItemFieldName:  streamItemFieldName,
		StreamItemWrapperRef: sd.PkgName + "." + protocOneofWrapperRef(message.VarName, streamItemFieldName),
	}
}

// nativeMetadataAttribute returns a detached primitive or primitive-array
// value for gRPC metadata. Named service declarations are recursively removed
// while their validation and default contracts remain on the wire copy.
func nativeMetadataAttribute(source *expr.AttributeExpr) *expr.AttributeExpr {
	if userType, ok := source.Type.(expr.UserType); ok {
		result := nativeMetadataAttribute(userType.Attribute())
		mergeNativeMetadataContract(result, source)
		return result
	}
	result := &expr.AttributeExpr{
		Description:  source.Description,
		DefaultValue: source.DefaultValue,
		UserExamples: source.UserExamples,
	}
	if source.Validation != nil {
		result.Validation = source.Validation.Dup()
	}
	if source.Meta != nil {
		result.Meta = source.Meta.Dup()
	}
	switch actual := source.Type.(type) {
	case expr.Primitive:
		result.Type = actual
	case *expr.Array:
		result.Type = &expr.Array{
			ElemType:         nativeMetadataAttribute(actual.ElemType),
			NonNullableElems: actual.NonNullableElems,
		}
	default:
		panic(fmt.Sprintf("invalid gRPC metadata type %s", source.Type.Name()))
	}
	stripMetadataServiceNames(result)
	return result
}

// mergeNativeMetadataContract applies constraints authored on an alias use to
// the detached contract inherited from the alias declaration.
func mergeNativeMetadataContract(target, source *expr.AttributeExpr) {
	if source.Description != "" {
		target.Description = source.Description
	}
	if source.DefaultValue != nil {
		target.DefaultValue = source.DefaultValue
	}
	if source.Validation != nil {
		if target.Validation == nil {
			target.Validation = source.Validation.Dup()
		} else {
			target.Validation.Merge(source.Validation)
		}
	}
	if source.Meta != nil {
		if target.Meta == nil {
			target.Meta = make(expr.MetaExpr)
		}
		for name, values := range source.Meta {
			target.Meta[name] = append([]string(nil), values...)
		}
	}
	stripMetadataServiceNames(target)
}

// stripMetadataServiceNames removes Go service declaration overrides from a
// value rendered entirely in the generated gRPC client or server package.
func stripMetadataServiceNames(attribute *expr.AttributeExpr) {
	for name := range attribute.Meta {
		if strings.HasPrefix(name, "struct:") || name == "name:original" {
			delete(attribute.Meta, name)
		}
	}
}

// serviceTypeContext returns a context that resolves service declarations from
// the generated gRPC package for side.
func (d *ServicesData) serviceTypeContext(sd *ServiceData, side string) *codegen.AttributeContext {
	outputPackage := path.Join(d.GenPkg(), "grpc", sd.Service.PathName, side)
	return &codegen.AttributeContext{
		UseDefault: true,
		Scope:      d.ServiceAttributor(sd.Service.Name, outputPackage),
	}
}

// resultContext returns the method result and its frozen service or view
// declaration context for side.
func (d *ServicesData) resultContext(e *expr.GRPCEndpointExpr, sd *ServiceData, side string) (*expr.AttributeExpr, *codegen.AttributeContext) {
	md := sd.Service.Method(e.Name())
	if md.ViewedResult != nil {
		vresAtt := expr.AsObject(md.ViewedResult.Type).Attribute("projected")
		outputPackage := path.Join(d.GenPkg(), "grpc", sd.Service.PathName, side)
		return vresAtt, &codegen.AttributeContext{
			Pointer:    true,
			UseDefault: true,
			Scope:      d.ViewAttributor(sd.Service.Name, outputPackage),
		}
	}
	result := e.MethodExpr.Result
	return result, d.serviceTypeContext(sd, side).Enter(result)
}

// getPrimitive returns the primitive expression if the given expression is an alias to one
func getPrimitive(att *expr.AttributeExpr) *expr.AttributeExpr {
	if ut, ok := att.Type.(*expr.UserTypeExpr); ok {
		if _, ok := ut.Type.(expr.Primitive); ok {
			return ut.AttributeExpr
		}
		return getPrimitive(ut.AttributeExpr)
	}
	return nil
}

// unAlias returns the base attribute of the given attribute when it is an
// alias to a primitive type, the attribute itself otherwise.
func unAlias(at *expr.AttributeExpr) *expr.AttributeExpr {
	if prim := getPrimitive(at); prim != nil {
		return prim
	}
	return at
}

// isEmpty returns true if given type is empty.
func isEmpty(dt expr.DataType) bool {
	if dt == expr.Empty {
		return true
	}
	if o := expr.AsObject(dt); o != nil && len(*o) == 0 {
		return true
	}
	return false
}

// usesAnyType reports whether any of the given endpoints uses the Any type in
// its payload, result or, when includeErrors is true, error attributes. It is
// used to determine whether generated files need the structpb import.
func usesAnyType(endpoints []*expr.GRPCEndpointExpr, includeErrors bool) bool {
	for _, e := range endpoints {
		if hasAnyType(e.MethodExpr.Payload) || hasAnyType(e.MethodExpr.Result) {
			return true
		}
		if !includeErrors {
			continue
		}
		for _, er := range e.MethodExpr.Errors {
			if hasAnyType(er.AttributeExpr) {
				return true
			}
		}
	}
	return false
}

// hasAnyType reports whether the attribute uses Any without following a named
// type more than once.
func hasAnyType(att *expr.AttributeExpr) bool {
	return hasAnyTypeR(att, make(map[expr.UserType]struct{}))
}

// hasAnyTypeR walks arrays, maps, objects, unions, and named types.
func hasAnyTypeR(att *expr.AttributeExpr, seen map[expr.UserType]struct{}) bool {
	if att == nil {
		return false
	}
	if att.Type.Kind() == expr.AnyKind {
		return true
	}
	switch dt := att.Type.(type) {
	case expr.UserType:
		origin := dt.Origin()
		if _, ok := seen[origin]; ok {
			return false
		}
		seen[origin] = struct{}{}
		return hasAnyTypeR(dt.Attribute(), seen)
	case *expr.Object:
		for _, nat := range *dt {
			if hasAnyTypeR(nat.Attribute, seen) {
				return true
			}
		}
	case *expr.Array:
		return hasAnyTypeR(dt.ElemType, seen)
	case *expr.Map:
		return hasAnyTypeR(dt.KeyType, seen) || hasAnyTypeR(dt.ElemType, seen)
	case *expr.Union:
		for _, nat := range dt.Values {
			if hasAnyTypeR(nat.Attribute, seen) {
				return true
			}
		}
	}
	return false
}
