swagger: "2.0"
info:
  title: Cars Service
  description: HTTP service to lookup car models by body style.
  version: ""
host: localhost:8080
paths:
  /cars:
    get:
      tags:
      - cars
      summary: list cars
      description: |-
        Lists car models by body style.

        Required security scopes:
          * `stream:read`
      operationId: cars#list
      parameters:
      - name: style
        in: query
        description: The car body style.
        required: true
        type: string
        enum:
        - sedan
        - hatchback
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ListResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ListUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/ListInvalidScopesResponseBody'
      schemes:
      - http
      - ws
      security:
      - jwt: []
  /cars/login:
    post:
      tags:
      - cars
      summary: login cars
      description: Creates a valid JWT
      operationId: cars#login
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/LoginUnauthorizedResponseBody'
      schemes:
      - http
      - ws
      security:
      - basic: []
definitions:
  ListInvalidScopesResponseBody:
    title: ListInvalidScopesResponseBody
    type: string
    example: Quis velit.
  ListResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.car; view=default'
    type: object
    properties:
      body_style:
        type: string
        description: The car body style
        example: Vero odio odio id autem.
      make:
        type: string
        description: The make of the car
        example: Repellat repellendus rerum ex dolores facilis non.
      model:
        type: string
        description: The car model
        example: Aspernatur totam.
    example:
      body_style: Et similique voluptatem aut.
      make: Laudantium qui minima voluptatibus in incidunt.
      model: Rerum dolor.
    required:
    - make
    - model
    - body_style
  ListUnauthorizedResponseBody:
    title: ListUnauthorizedResponseBody
    type: string
    example: Nihil modi consequuntur impedit culpa dolor iste.
  LoginUnauthorizedResponseBody:
    title: LoginUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: In suscipit temporibus.
securityDefinitions:
  basic:
    type: basic
    description: Secures the login endpoint.
  jwt:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".
      **Security Scopes**:
        * `stream:read`: Read-only access
        * `stream:write`: Read and write access
