name: build
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20', '1.21']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Build
        run: make ci
      - name: Upload test coverage for deep source
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: cover.out

